// Bundles src/ into main.js, the single file Obsidian loads.
//   npm run build  -> one-off build
//   npm run dev    -> rebuild on every change in src/

import esbuild from "esbuild";

const watch = process.argv.includes("--watch");

const ctx = await esbuild.context({
  entryPoints: ["src/main.js"],
  outfile: "main.js",
  bundle: true,
  platform: "node", // keeps Node built-ins (fs, path, child_process) external
  format: "cjs",
  target: "es2020",
  // Provided by Obsidian/Electron at runtime. xterm is loaded from node_modules at runtime too.
  external: ["obsidian", "electron", "@xterm/*", "node-pty"],
  logLevel: "info",
  banner: { js: "/* Generated by esbuild from src/ — edit the files in src/, not this one. */" },
});

if (watch) {
  await ctx.watch();
} else {
  await ctx.rebuild();
  await ctx.dispose();
}
