/* Generated by esbuild from src/ — edit the files in src/, not this one. */
"use strict";
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/constants.js
var require_constants = __commonJS({
  "src/constants.js"(exports2, module2) {
    "use strict";
    var VIEW_TYPE2 = "open-terminal-view";
    var BLOCK_LANG2 = "terminal";
    var DEFAULT_SETTINGS2 = {
      // "auto", "powershell", "pwsh", "cmd" (Windows), "zsh", "bash" (macOS/Linux) or "custom"
      shell: "auto",
      customShell: "",
      // "bottom" (split panel below), "tab" (new tab) or "right" (right sidebar)
      location: "bottom",
      // Empty = auto-detect
      nodePath: "",
      harnessProviders: {
        pi: { executable: "" }
      },
      fontSize: 14
    };
    var SHELLS = {
      powershell: { cmd: "powershell.exe", args: ["-NoLogo"], win: true },
      pwsh: { cmd: "pwsh.exe", args: ["-NoLogo"], win: true },
      cmd: { cmd: "cmd.exe", args: [], win: true },
      zsh: { cmd: "/bin/zsh", args: ["-l"], win: false },
      bash: { cmd: "/bin/bash", args: ["-l"], win: false }
    };
    module2.exports = { VIEW_TYPE: VIEW_TYPE2, BLOCK_LANG: BLOCK_LANG2, DEFAULT_SETTINGS: DEFAULT_SETTINGS2, SHELLS };
  }
});

// src/shell.js
var require_shell = __commonJS({
  "src/shell.js"(exports2, module2) {
    "use strict";
    var fs = require("fs");
    var path2 = require("path");
    var { SHELLS } = require_constants();
    function getShell(settings) {
      if (settings.shell === "custom" && settings.customShell.trim()) {
        const parts = settings.customShell.trim().match(/"[^"]*"|\S+/g).map((p) => p.replace(/^"|"$/g, ""));
        return { cmd: parts[0], args: parts.slice(1) };
      }
      const isWin = process.platform === "win32";
      const picked = SHELLS[settings.shell];
      if (picked && picked.win === isWin) return picked;
      if (isWin) return SHELLS.powershell;
      return { cmd: process.env.SHELL || (process.platform === "darwin" ? "/bin/zsh" : "/bin/bash"), args: ["-l"] };
    }
    function resolveNodePath(settings) {
      if (settings.nodePath.trim()) return settings.nodePath.trim();
      const candidates = [];
      const dirs = (process.env.PATH || "").split(path2.delimiter);
      const exe = process.platform === "win32" ? "node.exe" : "node";
      for (const d of dirs) if (d) candidates.push(path2.join(d, exe));
      if (process.platform === "win32") {
        candidates.push(path2.join(process.env.ProgramFiles || "C:\\Program Files", "nodejs", "node.exe"));
        if (process.env.APPDATA) candidates.push(path2.join(process.env.APPDATA, "nvm", "current", "node.exe"));
      } else {
        candidates.push("/usr/local/bin/node", "/opt/homebrew/bin/node", "/usr/bin/node");
      }
      return candidates.find((c) => fs.existsSync(c)) || null;
    }
    function quoteArg(shellCmd, arg) {
      const shell2 = shellCmd.toLowerCase();
      if (shell2.includes("cmd")) return '"' + String(arg).replace(/"/g, '""') + '"';
      if (shell2.includes("powershell") || shell2.includes("pwsh")) return "'" + String(arg).replace(/'/g, "''") + "'";
      return "'" + String(arg).replace(/'/g, "'\\''") + "'";
    }
    function cdCommand(shellCmd, dir) {
      const shell2 = shellCmd.toLowerCase();
      if (shell2.includes("powershell") || shell2.includes("pwsh")) return `Set-Location -LiteralPath ${quoteArg(shellCmd, dir)}`;
      if (shell2.includes("cmd")) return `cd /d ${quoteArg(shellCmd, dir)}`;
      return `cd ${quoteArg(shellCmd, dir)}`;
    }
    function shellSeparator(shellCmd) {
      return shellCmd.toLowerCase().includes("cmd") ? "&&" : ";";
    }
    module2.exports = { getShell, resolveNodePath, quoteArg, cdCommand, shellSeparator };
  }
});

// src/terminal-session.js
var require_terminal_session = __commonJS({
  "src/terminal-session.js"(exports2, module2) {
    "use strict";
    var { spawn } = require("child_process");
    var TerminalSession = class {
      constructor(plugin, { cwd, command, env } = {}) {
        this.plugin = plugin;
        this.cwd = cwd;
        this.env = env;
        this.pendingCommand = command || null;
        this.host = null;
        this.term = null;
        this.fit = null;
        this.exited = false;
        this.disposed = false;
        this.lastActive = Date.now();
        this.parentEl = null;
        this.onDispose = null;
        this.onReveal = null;
        this.el = createDiv({ cls: "open-terminal-xterm" });
      }
      /** Shows the terminal inside parentEl (creates xterm the first time). */
      attach(parentEl) {
        if (this.disposed) return;
        this.detach();
        this.parentEl = parentEl;
        parentEl.appendChild(this.el);
        if (!this.term) this.createTerm();
        else this.term.refresh(0, this.term.rows - 1);
        this.resizeObserver = new ResizeObserver(() => this.resize());
        this.resizeObserver.observe(parentEl);
        this.resize();
        if (!this.host && !this.exited) this.startShell();
      }
      /** Removes the terminal from the DOM, keeping the shell alive. */
      detach() {
        if (this.resizeObserver) this.resizeObserver.disconnect();
        this.resizeObserver = null;
        this.parentEl = null;
        this.el.detach();
      }
      isAttached() {
        return !!this.parentEl && this.el.isConnected;
      }
      createTerm() {
        const { Terminal, FitAddon } = this.plugin.loadXterm();
        const css = getComputedStyle(document.body);
        const cssVar = (name, fallback) => css.getPropertyValue(name).trim() || fallback;
        const isMac = process.platform === "darwin";
        const monoFallback = "'SF Mono', SFMono-Regular, Menlo, Monaco, Consolas, 'Courier New', monospace";
        const fontFamily = isMac ? monoFallback : `${cssVar("--font-monospace", "Consolas")}, ${monoFallback}`;
        this.term = new Terminal({
          cursorBlink: true,
          cursorStyle: "bar",
          cursorWidth: 2,
          fontSize: this.plugin.settings.fontSize,
          fontFamily,
          letterSpacing: 0,
          lineHeight: isMac ? 1.25 : 1.1,
          fontWeight: "400",
          fontWeightBold: "600",
          macOptionIsMeta: isMac,
          scrollback: 5e3,
          allowProposedApi: true,
          theme: {
            background: cssVar("--background-primary", "#1e1e1e"),
            foreground: cssVar("--text-normal", "#dcddde"),
            cursor: cssVar("--text-accent", "#7f6df2"),
            cursorAccent: cssVar("--background-primary", "#1e1e1e"),
            selectionBackground: cssVar("--text-selection", "rgba(127,109,242,0.35)")
          }
        });
        this.fit = new FitAddon();
        this.term.loadAddon(this.fit);
        this.term.open(this.el);
        if (document.fonts && document.fonts.ready) {
          document.fonts.ready.then(() => {
            if (!this.term) return;
            this.term.options.fontFamily = fontFamily;
            this.resize();
          });
        }
        this.term.attachCustomKeyEventHandler((e) => {
          if (e.type !== "keydown") return true;
          const key = e.key.toLowerCase();
          if (e.ctrlKey && key === "c" && this.term.hasSelection()) {
            navigator.clipboard.writeText(this.term.getSelection());
            this.term.clearSelection();
            return false;
          }
          if (e.ctrlKey && e.shiftKey && key === "c") return false;
          if (e.ctrlKey && key === "v") {
            e.preventDefault();
            navigator.clipboard.readText().then((text) => this.term && this.term.paste(text));
            return false;
          }
          return true;
        });
        this.term.onData((data) => {
          this.lastActive = Date.now();
          if (this.host) this.send({ t: "i", d: data });
          else if (this.exited) this.startShell();
        });
      }
      startShell() {
        if (!this.term || !this.cwd || this.disposed) return;
        this.exited = false;
        const node = this.plugin.resolveNodePath();
        if (!node) {
          this.term.writeln("\x1B[31mNode.js not found. Set the Node.js path in the plugin settings.\x1B[0m");
          return;
        }
        const { cmd, args } = this.plugin.getShell();
        this.fitNow();
        const hostArgs = [this.plugin.hostPath(), this.cwd, cmd, String(this.term.cols), String(this.term.rows), ...args];
        const host = spawn(node, hostArgs, {
          cwd: this.plugin.pluginDir(),
          env: { ...process.env, ...this.env },
          windowsHide: true,
          stdio: ["pipe", "pipe", "pipe"]
        });
        this.host = host;
        this.lastSize = null;
        host.stdout.setEncoding("utf8");
        host.stderr.setEncoding("utf8");
        host.stdout.on("data", (d) => {
          if (this.term) this.term.write(d);
          if (this.pendingCommand) {
            const cmd2 = this.pendingCommand;
            this.pendingCommand = null;
            setTimeout(() => this.send({ t: "i", d: cmd2 + "\r" }), 400);
          }
        });
        host.stderr.on("data", (d) => this.term && this.term.write(`\x1B[31m${d.replace(/\n/g, "\r\n")}\x1B[0m`));
        host.on("error", (err) => {
          if (this.term) this.term.writeln(`\x1B[31mFailed to start the terminal: ${err.message}\x1B[0m`);
        });
        host.on("exit", () => {
          if (this.host !== host) return;
          this.host = null;
          this.exited = true;
          if (this.term) this.term.write("\r\n\x1B[2m[process exited \u2014 press any key to restart]\x1B[0m\r\n");
        });
      }
      send(msg) {
        if (this.host && this.host.stdin.writable) this.host.stdin.write(JSON.stringify(msg) + "\n");
      }
      /** Stops the shell (the terminal stays visible and restarts on the next key press). */
      kill() {
        const host = this.host;
        if (!host) return;
        this.send({ t: "k" });
        setTimeout(() => {
          try {
            host.kill();
          } catch {
          }
        }, 1e3);
      }
      /** Restarts the shell in the same folder. */
      restart() {
        const host = this.host;
        if (host) {
          this.host = null;
          try {
            host.kill();
          } catch {
          }
        }
        if (this.term) this.term.reset();
        this.startShell();
      }
      /** Is the shell running (process alive)? */
      isAlive() {
        return !!this.host && !!this.term;
      }
      /** Text of the cursor's line, up to the cursor position. */
      cursorLineText() {
        if (!this.term) return "";
        const b = this.term.buffer.active;
        const line = b.getLine(b.baseY + b.cursorY);
        return line ? line.translateToString(true, 0, b.cursorX) : "";
      }
      /** Is the shell idle at its prompt (no program running)? */
      isAtPrompt() {
        if (!this.isAlive() || this.pendingCommand) return false;
        const text = this.cursorLineText().trimEnd();
        return /^PS [^>]*>$/.test(text) || /^[A-Za-z]:\\[^>]*>$/.test(text) || /[$#%]$/.test(text);
      }
      /** Types text into the terminal; submit=true presses Enter. */
      sendText(text, { submit = true } = {}) {
        this.lastActive = Date.now();
        this.send({ t: "i", d: text });
        if (submit) setTimeout(() => this.send({ t: "i", d: "\r" }), 150);
      }
      reveal() {
        if (this.onReveal) this.onReveal();
        this.focus();
      }
      focus() {
        if (this.term) this.term.focus();
      }
      fitNow() {
        if (!this.fit || !this.el.isShown()) return;
        try {
          this.fit.fit();
        } catch {
        }
      }
      resize() {
        if (!this.term) return;
        const { cols, rows } = this.term;
        this.fitNow();
        if (this.term.cols !== cols || this.term.rows !== rows || !this.lastSize) {
          this.lastSize = true;
          this.send({ t: "r", c: this.term.cols, r: this.term.rows });
        }
      }
      dispose() {
        if (this.disposed) return;
        this.disposed = true;
        this.detach();
        if (this.onDispose) this.onDispose();
        this.kill();
        this.host = null;
        if (this.term) {
          this.term.dispose();
          this.term = null;
        }
      }
    };
    module2.exports = { TerminalSession };
  }
});

// src/terminal-view.js
var require_terminal_view = __commonJS({
  "src/terminal-view.js"(exports2, module2) {
    "use strict";
    var { ItemView } = require("obsidian");
    var path2 = require("path");
    var { VIEW_TYPE: VIEW_TYPE2 } = require_constants();
    var { TerminalSession } = require_terminal_session();
    var TerminalView2 = class extends ItemView {
      constructor(leaf, plugin) {
        super(leaf);
        this.plugin = plugin;
        this.cwd = null;
        this.session = null;
      }
      getViewType() {
        return VIEW_TYPE2;
      }
      getDisplayText() {
        return this.cwd ? `Terminal: ${path2.basename(this.cwd)}` : "Terminal";
      }
      getIcon() {
        return "terminal-square";
      }
      getState() {
        return { cwd: this.cwd };
      }
      async setState(state, result) {
        if (state && state.cwd && !this.session) this.startSession(state.cwd, state.command, state.env);
        await super.setState(state, result);
      }
      async onOpen() {
        this.contentEl.empty();
        this.contentEl.addClass("open-terminal-container");
        setTimeout(() => {
          if (!this.session) this.startSession(this.plugin.getVaultPath());
        }, 150);
      }
      startSession(cwd, command, env) {
        if (!cwd) return;
        this.cwd = cwd;
        this.session = new TerminalSession(this.plugin, { cwd, command, env });
        this.session.onReveal = () => {
          this.app.workspace.revealLeaf(this.leaf);
          this.app.workspace.setActiveLeaf(this.leaf, { focus: true });
        };
        this.session.attach(this.contentEl);
        this.leaf.updateHeader && this.leaf.updateHeader();
        this.session.focus();
      }
      // Kept for compatibility with code that uses the view directly
      isAlive() {
        return !!this.session && this.session.isAlive();
      }
      isAtPrompt() {
        return !!this.session && this.session.isAtPrompt();
      }
      sendText(text, opts) {
        if (this.session) this.session.sendText(text, opts);
      }
      reveal() {
        if (this.session) this.session.reveal();
      }
      onResize() {
        if (this.session) this.session.resize();
      }
      async onClose() {
        if (this.session) {
          this.session.dispose();
          this.session = null;
        }
      }
    };
    module2.exports = { TerminalView: TerminalView2 };
  }
});

// src/terminal-block.js
var require_terminal_block = __commonJS({
  "src/terminal-block.js"(exports2, module2) {
    "use strict";
    var { MarkdownRenderChild, setIcon } = require("obsidian");
    var path2 = require("path");
    var TerminalBlockChild = class extends MarkdownRenderChild {
      constructor(el, blocks, session, key, sourcePath) {
        super(el);
        this.blocks = blocks;
        this.session = session;
        this.key = key;
        this.sourcePath = sourcePath;
      }
      onload() {
        const el = this.containerEl;
        el.empty();
        el.addClass("open-terminal-block");
        const toolbar = el.createDiv({ cls: "open-terminal-block-toolbar" });
        setIcon(toolbar.createSpan({ cls: "open-terminal-block-icon" }), "terminal-square");
        toolbar.createSpan({ cls: "open-terminal-block-title", text: path2.basename(this.session.cwd || "") || "Terminal" });
        toolbar.setAttr("title", this.session.cwd || "");
        const button = (icon, label, onClick) => {
          const b = toolbar.createEl("button", { cls: "clickable-icon open-terminal-block-button", attr: { "aria-label": label } });
          setIcon(b, icon);
          this.registerDomEvent(b, "click", (e) => {
            e.stopPropagation();
            onClick();
          });
        };
        button("rotate-ccw", "Restart terminal", () => this.session.restart());
        button("square", "Stop process", () => this.session.kill());
        this.body = el.createDiv({ cls: "open-terminal-block-body" });
        for (const ev of ["pointerdown", "mousedown", "click", "dblclick", "wheel", "keydown", "keyup", "contextmenu"]) {
          this.registerDomEvent(this.body, ev, (e) => e.stopPropagation());
        }
        this.session.onReveal = () => el.scrollIntoView({ block: "nearest" });
        whenConnected(el, () => {
          if (this.unloaded) return;
          this.fitToCanvasNode();
          this.session.attach(this.body);
        });
      }
      /** In Canvas, makes the terminal fill the card's full height. */
      fitToCanvasNode() {
        const nodeEl = this.containerEl.closest(".canvas-node-content");
        if (!nodeEl) return;
        this.containerEl.addClass("is-canvas");
        const apply = () => this.containerEl.style.height = `${nodeEl.clientHeight}px`;
        apply();
        this.nodeObserver = new ResizeObserver(apply);
        this.nodeObserver.observe(nodeEl);
      }
      onunload() {
        this.unloaded = true;
        if (this.nodeObserver) this.nodeObserver.disconnect();
        if (this.session.parentEl === this.body) this.session.detach();
        this.blocks.scheduleOrphanCheck(this.key, this.sourcePath);
      }
    };
    function whenConnected(el, cb, tries = 120) {
      if (el.isConnected) return cb();
      if (tries <= 0) return;
      requestAnimationFrame(() => whenConnected(el, cb, tries - 1));
    }
    module2.exports = { TerminalBlockChild };
  }
});

// src/block-sessions.js
var require_block_sessions = __commonJS({
  "src/block-sessions.js"(exports2, module2) {
    "use strict";
    var { TFile: TFile2 } = require("obsidian");
    var path2 = require("path");
    var { BLOCK_LANG: BLOCK_LANG2 } = require_constants();
    var { TerminalSession } = require_terminal_session();
    var { TerminalBlockChild } = require_terminal_block();
    function parseBlockOptions(source) {
      const opts = {};
      for (const line of source.split(/\r?\n/)) {
        const m = line.match(/^\s*([A-Za-z]+)\s*:\s*(.*?)\s*$/);
        if (m) opts[m[1].toLowerCase()] = m[2];
      }
      return opts;
    }
    function blockKey2(source, sourcePath) {
      const { id } = parseBlockOptions(source);
      return id ? `id:${id}` : `${sourcePath}::${source.trim()}`;
    }
    function newBlockId() {
      return Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
    }
    function newBlockMarkdown2() {
      return "```" + BLOCK_LANG2 + "\nid: " + newBlockId() + "\n```";
    }
    var BlockSessions2 = class {
      constructor(plugin, { language = BLOCK_LANG2, createSession, keyFor = blockKey2 } = {}) {
        this.plugin = plugin;
        this.language = language;
        this.keyFor = keyFor;
        this.createSession = createSession || ((opts, ctx) => new TerminalSession(this.plugin, {
          cwd: this.resolveCwd(opts.cwd, ctx.sourcePath),
          command: opts.command
        }));
        this.sessions = /* @__PURE__ */ new Map();
        this.orphanTimers = /* @__PURE__ */ new Map();
      }
      /** Markdown code block processor for a terminal-like block. */
      async process(source, el, ctx) {
        const opts = parseBlockOptions(source);
        const key = this.keyFor(source, ctx.sourcePath);
        let session = this.sessions.get(key);
        if (!session || session.disposed) {
          session = await this.createSession(opts, ctx, source);
          if (!session) return;
          this.sessions.set(key, session);
        }
        ctx.addChild(new TerminalBlockChild(el, this, session, key, ctx.sourcePath));
      }
      /** Block cwd: absolute, relative to the vault root, or (default) the folder of the file containing the block. */
      resolveCwd(cwd, sourcePath) {
        const vault = this.plugin.getVaultPath();
        if (cwd) return path2.isAbsolute(cwd) ? cwd : path2.join(vault, cwd);
        const file = this.plugin.app.vault.getAbstractFileByPath(sourcePath);
        return file instanceof TFile2 ? this.plugin.getAbsolutePath(file.parent) : vault;
      }
      /** Sessions currently shown on screen, most recently used first. */
      visible() {
        return [...this.sessions.values()].filter((s) => !s.disposed && s.isAttached()).sort((a, b) => b.lastActive - a.lastActive);
      }
      /**
       * Called when a block leaves the DOM. Canvas unloads off-screen cards,
       * so the shell is only stopped if the block no longer exists in the file.
       */
      scheduleOrphanCheck(key, sourcePath) {
        clearTimeout(this.orphanTimers.get(key));
        this.orphanTimers.set(
          key,
          setTimeout(async () => {
            this.orphanTimers.delete(key);
            const session = this.sessions.get(key);
            if (!session || session.isAttached()) return;
            const file = this.plugin.app.vault.getAbstractFileByPath(sourcePath);
            let keys = /* @__PURE__ */ new Set();
            if (file instanceof TFile2) {
              try {
                keys = this.keysInFile(await this.plugin.app.vault.cachedRead(file), file);
              } catch {
                return;
              }
            }
            if (keys === null) return;
            if (!keys.has(key) && !session.isAttached()) {
              session.dispose();
              this.sessions.delete(key);
            }
          }, 5e3)
        );
      }
      keysInFile(content, file) {
        let texts = [content];
        if (file.extension === "canvas") {
          try {
            const data = JSON.parse(content);
            texts = (data.nodes || []).filter((n) => n.type === "text").map((n) => n.text || "");
          } catch {
            return null;
          }
        }
        const keys = /* @__PURE__ */ new Set();
        const languages = Array.isArray(this.language) ? this.language : [this.language];
        const languagePattern = languages.map((language) => language.replace(/[.*+?^${}()|[\\]\\]/g, "\\\\$&")).join("|");
        const fence = new RegExp("^(`{3,}|~{3,})[ \\t]*(?:" + languagePattern + ")[ \\t]*\\r?\\n([\\s\\S]*?)^\\1[ \\t]*$", "gm");
        for (const text of texts) {
          for (const m of text.matchAll(fence)) keys.add(this.keyFor(m[2], file.path));
        }
        return keys;
      }
      disposeAll() {
        for (const session of this.sessions.values()) session.dispose();
        this.sessions.clear();
        for (const timer of this.orphanTimers.values()) clearTimeout(timer);
        this.orphanTimers.clear();
      }
    };
    module2.exports = { BlockSessions: BlockSessions2, parseBlockOptions, blockKey: blockKey2, newBlockMarkdown: newBlockMarkdown2 };
  }
});

// src/pi-harness.js
var require_pi_harness = __commonJS({
  "src/pi-harness.js"(exports2, module2) {
    "use strict";
    var crypto = require("crypto");
    var HARNESS_LANGUAGE2 = "pi-harness";
    var GENERIC_HARNESS_LANGUAGE2 = "agent-harness";
    var SUPPORTED_AGENT = "pi";
    var SUPPORTED_BRIDGE = "open-terminal";
    var HARNESS_FENCE = new RegExp("^\\s*```(?:" + HARNESS_LANGUAGE2 + "|" + GENERIC_HARNESS_LANGUAGE2 + ")[ \\t]*\\r?\\n([\\s\\S]*?)\\r?\\n```\\s*$");
    function newPiHarnessId() {
      const suffix = typeof crypto.randomUUID === "function" ? crypto.randomUUID() : crypto.randomBytes(16).toString("hex");
      return `pi-${suffix}`;
    }
    function createPiHarnessMarkdown(id = newPiHarnessId()) {
      return `\`\`\`${HARNESS_LANGUAGE2}
id: ${id}
agent: ${SUPPORTED_AGENT}
bridge: ${SUPPORTED_BRIDGE}
\`\`\``;
    }
    function parseHarnessNode(text) {
      const match = typeof text === "string" ? text.match(HARNESS_FENCE) : null;
      if (!match) return invalid("The node must contain a pi-harness or agent-harness code block.");
      const values = {};
      const errors = [];
      for (const line of match[1].split(/\r?\n/)) {
        if (!line.trim()) continue;
        const field = line.match(/^\s*([A-Za-z]+)\s*:\s*(.*?)\s*$/);
        if (!field) {
          errors.push(`Invalid harness field: ${line}`);
          continue;
        }
        const key = field[1].toLowerCase();
        if (Object.prototype.hasOwnProperty.call(values, key)) {
          errors.push(`Duplicate harness field: ${key}`);
          continue;
        }
        values[key] = field[2];
      }
      if (!values.id) errors.push("Harness ID is required.");
      const provider = values.provider || values.agent;
      if (!provider) errors.push("Harness provider is required.");
      if (errors.length) return { valid: false, harness: null, errors };
      return {
        valid: true,
        harness: { id: values.id, agent: provider, provider, bridge: values.bridge || null, config: values },
        errors: []
      };
    }
    function parsePiHarnessNode(text) {
      const result = parseHarnessNode(text);
      if (!result.valid) {
        const errors = result.errors.map((error) => error === "Harness provider is required." ? "Harness agent is required." : error);
        if (errors.length === 1 && errors[0] === "The node must contain a pi-harness or agent-harness code block.") {
          return invalid("The node must contain a pi-harness code block.");
        }
        return { ...result, errors };
      }
      if (result.harness.agent !== SUPPORTED_AGENT) return invalid(`Unsupported agent "${result.harness.agent}".`);
      if (result.harness.bridge && result.harness.bridge !== SUPPORTED_BRIDGE) return invalid(`Unsupported bridge "${result.harness.bridge}".`);
      return {
        valid: true,
        harness: { id: result.harness.id, agent: result.harness.agent, bridge: result.harness.bridge },
        errors: []
      };
    }
    function parseHarnessSource(source) {
      const text = typeof source === "string" ? source : "";
      return parseHarnessNode(["```agent-harness", text, "```"].join("\n"));
    }
    function invalid(error) {
      return { valid: false, harness: null, errors: [error] };
    }
    function findDuplicateHarnessIds(nodes) {
      const nodeIdsByHarnessId = /* @__PURE__ */ new Map();
      for (const node of nodes || []) {
        if (!node || node.type !== "text") continue;
        const declaration = parseHarnessNode(node.text);
        if (!declaration.valid) continue;
        const nodeIds = nodeIdsByHarnessId.get(declaration.harness.id) || [];
        nodeIds.push(node.id);
        nodeIdsByHarnessId.set(declaration.harness.id, nodeIds);
      }
      return [...nodeIdsByHarnessId].filter(([, nodeIds]) => nodeIds.length > 1).map(([harnessId, nodeIds]) => ({ harnessId, nodeIds }));
    }
    module2.exports = {
      HARNESS_LANGUAGE: HARNESS_LANGUAGE2,
      GENERIC_HARNESS_LANGUAGE: GENERIC_HARNESS_LANGUAGE2,
      SUPPORTED_AGENT,
      SUPPORTED_BRIDGE,
      createPiHarnessMarkdown,
      findDuplicateHarnessIds,
      newPiHarnessId,
      parseHarnessNode,
      parseHarnessSource,
      parsePiHarnessNode
    };
  }
});

// src/canvas.js
var require_canvas = __commonJS({
  "src/canvas.js"(exports2, module2) {
    "use strict";
    var { ItemView, Notice: Notice2, TFile: TFile2 } = require("obsidian");
    var { newBlockMarkdown: newBlockMarkdown2 } = require_block_sessions();
    var { createPiHarnessMarkdown } = require_pi_harness();
    function isCanvasView(view) {
      return Boolean(view && view.getViewType() === "canvas" && view.canvas && view.file instanceof TFile2);
    }
    function openCanvasViews(app) {
      const active = app.workspace.getActiveViewOfType(ItemView);
      const views = [active, ...app.workspace.getLeavesOfType("canvas").map((leaf) => leaf.view)];
      const ordered = [];
      for (const view of views) {
        if (!isCanvasView(view) || ordered.some((known) => known.file.path === view.file.path)) continue;
        ordered.push(view);
      }
      return ordered;
    }
    function openCanvasPaths(app) {
      return openCanvasViews(app).map((view) => view.file.path);
    }
    function liveCanvasContent(app, canvasPath) {
      const view = openCanvasViews(app).find((candidate) => candidate.file.path === canvasPath);
      const data = view && typeof view.canvas.getData === "function" ? view.canvas.getData() : null;
      return data ? JSON.stringify(data) : null;
    }
    function getActiveCanvas2(app) {
      const view = app.workspace.getActiveViewOfType(ItemView);
      return isCanvasView(view) ? view.canvas : null;
    }
    function addTerminalToCanvas2(canvas) {
      if (!canCreateTextNodes(canvas)) {
        new Notice2("This Obsidian version doesn't allow plugins to create cards. Create a text card with a ```terminal block instead.");
        return;
      }
      const center = canvasCenter(canvas);
      canvas.createTextNode({
        pos: center,
        position: "center",
        size: { width: 640, height: 380 },
        text: newBlockMarkdown2(),
        focus: false,
        save: true
      });
      if (typeof canvas.requestSave === "function") canvas.requestSave();
    }
    function addPiHarnessToCanvas2(canvas) {
      if (!canCreateTextNodes(canvas)) {
        new Notice2("This Obsidian version doesn't allow plugins to create cards. Create a text card with a pi-harness block instead.");
        return;
      }
      canvas.createTextNode({
        pos: canvasCenter(canvas),
        position: "center",
        size: { width: 640, height: 380 },
        text: createPiHarnessMarkdown(),
        focus: false,
        save: true
      });
      if (typeof canvas.requestSave === "function") canvas.requestSave();
    }
    function canCreateTextNodes(canvas) {
      return typeof canvas.createTextNode === "function";
    }
    function canvasCenter(canvas) {
      return typeof canvas.posCenter === "function" ? canvas.posCenter() : { x: 0, y: 0 };
    }
    module2.exports = { getActiveCanvas: getActiveCanvas2, openCanvasPaths, liveCanvasContent, addPiHarnessToCanvas: addPiHarnessToCanvas2, addTerminalToCanvas: addTerminalToCanvas2 };
  }
});

// src/settings-tab.js
var require_settings_tab = __commonJS({
  "src/settings-tab.js"(exports2, module2) {
    "use strict";
    var { PluginSettingTab, Setting } = require("obsidian");
    var OpenTerminalSettingTab2 = class extends PluginSettingTab {
      constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
      }
      display() {
        const { containerEl } = this;
        containerEl.empty();
        const s = this.plugin.settings;
        const save = () => this.plugin.saveSettings();
        new Setting(containerEl).setName("Shell").setDesc("Shell launched inside the embedded terminal.").addDropdown((dd) => {
          dd.addOption("auto", "Automatic (recommended)");
          if (process.platform === "win32") {
            dd.addOption("powershell", "Windows PowerShell");
            dd.addOption("pwsh", "PowerShell 7 (pwsh)");
            dd.addOption("cmd", "Command Prompt (cmd)");
          } else {
            dd.addOption("zsh", "Zsh");
            dd.addOption("bash", "Bash");
          }
          dd.addOption("custom", "Custom");
          dd.setValue(s.shell).onChange(async (v) => {
            s.shell = v;
            await save();
            this.display();
          });
        });
        if (s.shell === "custom") {
          new Setting(containerEl).setName("Custom shell").setDesc('Executable and arguments. E.g.: "C:\\Program Files\\Git\\bin\\bash.exe" --login').addText(
            (t) => t.setValue(s.customShell).onChange(async (v) => {
              s.customShell = v;
              await save();
            })
          );
        }
        new Setting(containerEl).setName("Where to open").addDropdown(
          (dd) => dd.addOption("bottom", "Split panel below").addOption("tab", "New tab").addOption("right", "Right sidebar").setValue(s.location).onChange(async (v) => {
            s.location = v;
            await save();
          })
        );
        new Setting(containerEl).setName("Pi executable").setDesc('Pi executable for managed Canvas harnesses. Leave empty to use "pi" from PATH.').addText(
          (t) => t.setPlaceholder("pi").setValue(s.harnessProviders.pi.executable).onChange(async (v) => {
            s.harnessProviders.pi.executable = v;
            await save();
          })
        );
        new Setting(containerEl).setName("Font size").setDesc("Applies to terminals opened after the change.").addSlider(
          (sl) => sl.setLimits(9, 24, 1).setValue(s.fontSize).setDynamicTooltip().onChange(async (v) => {
            s.fontSize = v;
            await save();
          })
        );
        new Setting(containerEl).setName("Node.js path").setDesc(`Leave empty to auto-detect. Detected: ${this.plugin.resolveNodePath() || "none"}`).addText(
          (t) => t.setPlaceholder("C:\\Program Files\\nodejs\\node.exe").setValue(s.nodePath).onChange(async (v) => {
            s.nodePath = v;
            await save();
          })
        );
      }
    };
    module2.exports = { OpenTerminalSettingTab: OpenTerminalSettingTab2 };
  }
});

// src/pi-bridge-transport.js
var require_pi_bridge_transport = __commonJS({
  "src/pi-bridge-transport.js"(exports2, module2) {
    "use strict";
    var crypto = require("crypto");
    var fs = require("fs/promises");
    var os = require("os");
    var path2 = require("path");
    var PROTOCOL_VERSION = 1;
    var SESSION_DIRECTORY_NAME = "open-terminal-pi";
    var WRITE_ID = /^write-[A-Za-z0-9-]+$/;
    var BridgeProtocolError = class extends Error {
      constructor(message) {
        super(message);
        this.name = "BridgeProtocolError";
      }
    };
    function randomId(prefix) {
      const value = typeof crypto.randomUUID === "function" ? crypto.randomUUID() : crypto.randomBytes(16).toString("hex");
      return `${prefix}-${value}`;
    }
    async function createBridgeSession({ temporaryRoot = os.tmpdir() } = {}) {
      const sessionId = randomId("session");
      const directory = path2.join(temporaryRoot, SESSION_DIRECTORY_NAME, sessionId);
      const session = {
        protocolVersion: PROTOCOL_VERSION,
        sessionId,
        bridgeToken: crypto.randomBytes(32).toString("base64url"),
        directory,
        canvasStatePath: path2.join(directory, "canvas-state.json"),
        outboxDirectory: path2.join(directory, "outbox"),
        writeProcessedDirectory: path2.join(directory, "write-processed"),
        writeAcknowledgementsDirectory: path2.join(directory, "write-acks"),
        writeErrorsDirectory: path2.join(directory, "write-errors"),
        sessionPath: path2.join(directory, "session.json")
      };
      await Promise.all([
        fs.mkdir(session.outboxDirectory, { recursive: true, mode: 448 }),
        fs.mkdir(session.writeProcessedDirectory, { recursive: true, mode: 448 }),
        fs.mkdir(session.writeAcknowledgementsDirectory, { recursive: true, mode: 448 }),
        fs.mkdir(session.writeErrorsDirectory, { recursive: true, mode: 448 })
      ]);
      return session;
    }
    function createCanvasWriteOperation({ harnessId, bridgeToken, canvasPath, harnessNodeId, targetNodeId, content, mode = "replace" }) {
      const operation = {
        version: PROTOCOL_VERSION,
        operationId: randomId("write"),
        operation: "write_canvas_node",
        harnessId,
        bridgeToken,
        canvasPath,
        harnessNodeId,
        targetNodeId,
        content,
        mode,
        createdAt: (/* @__PURE__ */ new Date()).toISOString()
      };
      validateCanvasWriteOperation(operation);
      return operation;
    }
    function validateCanvasWriteOperation(operation, expected = {}) {
      if (!operation || typeof operation !== "object" || operation.version !== PROTOCOL_VERSION) throw new BridgeProtocolError("Canvas write operation has an unsupported protocol version.");
      for (const field of ["operationId", "harnessId", "bridgeToken", "canvasPath", "harnessNodeId", "targetNodeId", "content", "createdAt"]) {
        if (typeof operation[field] !== "string" || !operation[field]) throw new BridgeProtocolError(`Canvas write field "${field}" is required.`);
      }
      if (operation.operation !== "write_canvas_node") throw new BridgeProtocolError("Unsupported Canvas operation.");
      if (!WRITE_ID.test(operation.operationId)) throw new BridgeProtocolError("Canvas operation ID is invalid.");
      if (!["replace", "append"].includes(operation.mode)) throw new BridgeProtocolError("Canvas write mode is invalid.");
      if (expected.harnessId && operation.harnessId !== expected.harnessId) throw new BridgeProtocolError("Canvas operation targets a different harness.");
      if (expected.bridgeToken && operation.bridgeToken !== expected.bridgeToken) throw new BridgeProtocolError("Canvas operation token is not authorized for this session.");
      return operation;
    }
    async function writeCanvasWriteOperation(session, operation) {
      validateCanvasWriteOperation(operation, { bridgeToken: session.bridgeToken, harnessId: session.harnessId });
      const operationPath = path2.join(session.outboxDirectory, `${operation.operationId}.json`);
      await writeJsonAtomically(operationPath, operation);
      return operationPath;
    }
    async function waitForWriteAcknowledgement(session, operationId, { timeoutMs = 1e4, pollIntervalMs = 100 } = {}) {
      const acknowledgementPath = path2.join(session.writeAcknowledgementsDirectory, `${operationId}.json`);
      const deadline = Date.now() + timeoutMs;
      while (Date.now() <= deadline) {
        const content = await readFileOrNull(acknowledgementPath);
        if (content !== null) {
          let acknowledgement;
          try {
            acknowledgement = JSON.parse(content);
          } catch {
            throw new BridgeProtocolError(`Canvas acknowledgement for "${operationId}" is not valid JSON.`);
          }
          return validateCanvasWriteAcknowledgement(acknowledgement, { operationId, harnessId: session.harnessId });
        }
        await sleep(pollIntervalMs);
      }
      throw new BridgeProtocolError(`Timed out waiting for Canvas acknowledgement of "${operationId}".`);
    }
    function validateCanvasWriteAcknowledgement(acknowledgement, expected = {}) {
      if (!acknowledgement || acknowledgement.version !== PROTOCOL_VERSION) throw new BridgeProtocolError("Canvas acknowledgement has an unsupported protocol version.");
      for (const field of ["operationId", "harnessId", "status", "receivedAt"]) {
        if (typeof acknowledgement[field] !== "string" || !acknowledgement[field]) throw new BridgeProtocolError(`Canvas acknowledgement field "${field}" is required.`);
      }
      if (!WRITE_ID.test(acknowledgement.operationId)) throw new BridgeProtocolError("Canvas acknowledgement operation ID is invalid.");
      if (!["accepted", "rejected", "failed"].includes(acknowledgement.status)) throw new BridgeProtocolError(`Unsupported Canvas acknowledgement status "${acknowledgement.status}".`);
      if (expected.operationId && acknowledgement.operationId !== expected.operationId) throw new BridgeProtocolError("Canvas acknowledgement belongs to a different operation.");
      if (expected.harnessId && acknowledgement.harnessId !== expected.harnessId) throw new BridgeProtocolError("Canvas acknowledgement belongs to a different harness.");
      return acknowledgement;
    }
    async function writeCanvasWriteAcknowledgement(session, acknowledgement) {
      validateCanvasWriteAcknowledgement(acknowledgement, { harnessId: session.harnessId });
      const acknowledgementPath = path2.join(session.writeAcknowledgementsDirectory, `${acknowledgement.operationId}.json`);
      await writeJsonAtomically(acknowledgementPath, acknowledgement);
      return acknowledgementPath;
    }
    async function writeJsonAtomically(filePath, value) {
      const temporaryPath = `${filePath}.${process.pid}.${Date.now()}.tmp`;
      try {
        await fs.writeFile(temporaryPath, `${JSON.stringify(value, null, 2)}
`, { encoding: "utf8", mode: 384 });
        await fs.rename(temporaryPath, filePath);
      } catch (error) {
        await fs.rm(temporaryPath, { force: true });
        throw error;
      }
    }
    async function readFileOrNull(filePath) {
      try {
        return await fs.readFile(filePath, "utf8");
      } catch (error) {
        if (error && error.code === "ENOENT") return null;
        throw error;
      }
    }
    function sleep(milliseconds) {
      return new Promise((resolve) => setTimeout(resolve, milliseconds));
    }
    module2.exports = {
      BridgeProtocolError,
      PROTOCOL_VERSION,
      createBridgeSession,
      createCanvasWriteOperation,
      validateCanvasWriteOperation,
      validateCanvasWriteAcknowledgement,
      waitForWriteAcknowledgement,
      writeCanvasWriteAcknowledgement,
      writeCanvasWriteOperation
    };
  }
});

// src/harness-transport.js
var require_harness_transport = __commonJS({
  "src/harness-transport.js"(exports2, module2) {
    "use strict";
    module2.exports = require_pi_bridge_transport();
  }
});

// src/canvas-graph.js
var require_canvas_graph = __commonJS({
  "src/canvas-graph.js"(exports2, module2) {
    "use strict";
    var crypto = require("crypto");
    var path2 = require("path");
    var { parsePiHarnessNode } = require_pi_harness();
    var CanvasGraphError = class extends Error {
      constructor(message) {
        super(message);
        this.name = "CanvasGraphError";
      }
    };
    function parseCanvasGraph(content) {
      let graph;
      try {
        graph = typeof content === "string" ? JSON.parse(content) : content;
      } catch {
        throw new CanvasGraphError("The Canvas document is not valid JSON.");
      }
      if (!graph || !Array.isArray(graph.nodes) || !Array.isArray(graph.edges)) {
        throw new CanvasGraphError("The Canvas document must contain nodes and edges arrays.");
      }
      return graph;
    }
    function getIncomingSourceNodes(graph, harnessNodeId, { allowFiles = false, nodeId = null } = {}) {
      const nodesById = /* @__PURE__ */ new Map();
      for (const node of graph.nodes) {
        if (!node || typeof node.id !== "string" || !node.id) throw new CanvasGraphError("Canvas nodes must have IDs.");
        if (nodesById.has(node.id)) throw new CanvasGraphError(`Duplicate Canvas node ID "${node.id}".`);
        nodesById.set(node.id, node);
      }
      if (!nodesById.has(harnessNodeId)) throw new CanvasGraphError(`Harness node "${harnessNodeId}" was not found.`);
      const sources = [];
      const includedNodeIds = /* @__PURE__ */ new Set();
      for (const edge of graph.edges) {
        if (!edge || typeof edge.fromNode !== "string" || typeof edge.toNode !== "string") {
          throw new CanvasGraphError("Canvas edges must include fromNode and toNode IDs.");
        }
        if (!nodesById.has(edge.fromNode) || !nodesById.has(edge.toNode)) {
          throw new CanvasGraphError(`Canvas edge "${edge.id || "unknown"}" references a missing node.`);
        }
        if (edge.toNode !== harnessNodeId || includedNodeIds.has(edge.fromNode)) continue;
        const source = nodesById.get(edge.fromNode);
        if (nodeId && source.id !== nodeId) continue;
        if (source.type === "text") {
          if (typeof source.text !== "string") throw new CanvasGraphError(`Text source node "${source.id}" has no text content.`);
          includedNodeIds.add(source.id);
          sources.push({ id: source.id, type: source.type, title: sourceTitle(source), content: source.text });
          continue;
        }
        if (source.type === "file" && allowFiles) {
          includedNodeIds.add(source.id);
          sources.push({ id: source.id, type: source.type, file: source.file, title: source.file || source.id, content: "" });
          continue;
        }
        throw new CanvasGraphError(`Unsupported source node type "${source.type}" for node "${source.id}".`);
      }
      return sources;
    }
    function getOutgoingTargets(graph, harnessNodeId) {
      const nodesById = indexNodes(graph);
      if (!nodesById.has(harnessNodeId)) throw new CanvasGraphError(`Harness node "${harnessNodeId}" was not found.`);
      const targets = [];
      for (const edge of graph.edges) {
        if (edge.fromNode !== harnessNodeId) continue;
        const node = nodesById.get(edge.toNode);
        if (!node) throw new CanvasGraphError(`Canvas edge "${edge.id || "unknown"}" references a missing node.`);
        if (node.type === "text") {
          if (typeof node.text !== "string") throw new CanvasGraphError(`Text target node "${node.id}" has no text content.`);
          if (parsePiHarnessNode(node.text).valid) throw new CanvasGraphError(`Pi harness node "${node.id}" cannot be a write target.`);
          targets.push({ id: node.id, type: "text", label: sourceTitle(node), file: null });
        } else if (node.type === "file") {
          if (typeof node.file !== "string" || !node.file) throw new CanvasGraphError(`File target node "${node.id}" has no file path.`);
          targets.push({ id: node.id, type: "file", label: node.file, file: node.file });
        } else {
          throw new CanvasGraphError(`Unsupported target node type "${node.type}" for node "${node.id}".`);
        }
      }
      return targets;
    }
    function resolveOutgoingTarget(graph, harnessNodeId, targetNodeId) {
      const target = getOutgoingTargets(graph, harnessNodeId).find((candidate) => candidate.id === targetNodeId);
      if (!target) throw new CanvasGraphError(`Canvas node "${targetNodeId}" is not a direct outgoing target of harness "${harnessNodeId}".`);
      return target;
    }
    function buildConnections(graph, harnessNodeId) {
      const targets = getOutgoingTargets(graph, harnessNodeId);
      const incoming = getIncomingSourceNodes(graph, harnessNodeId, { allowFiles: true });
      const connections = incoming.map((node) => ({
        id: node.id,
        type: node.type,
        label: node.title,
        file: node.file || null,
        directions: ["incoming"]
      }));
      for (const target of targets) {
        const existing = connections.find((node) => node.id === target.id);
        if (existing) existing.directions.push("outgoing");
        else connections.push({ id: target.id, type: target.type, label: target.label, file: target.file, directions: ["outgoing"] });
      }
      return connections;
    }
    function indexNodes(graph) {
      const nodesById = /* @__PURE__ */ new Map();
      for (const node of graph.nodes) {
        if (!node || typeof node.id !== "string" || !node.id) throw new CanvasGraphError("Canvas nodes must have IDs.");
        if (nodesById.has(node.id)) throw new CanvasGraphError(`Duplicate Canvas node ID "${node.id}".`);
        nodesById.set(node.id, node);
      }
      for (const edge of graph.edges) {
        if (!edge || typeof edge.fromNode !== "string" || typeof edge.toNode !== "string") throw new CanvasGraphError("Canvas edges must include fromNode and toNode IDs.");
        if (!nodesById.has(edge.fromNode) || !nodesById.has(edge.toNode)) throw new CanvasGraphError(`Canvas edge "${edge.id || "unknown"}" references a missing node.`);
      }
      return nodesById;
    }
    async function resolveIncomingSourceNodes(graph, harnessNodeId, readFile, options = {}) {
      if (typeof readFile !== "function") throw new CanvasGraphError("A vault file resolver is required for file Canvas nodes.");
      const sources = getIncomingSourceNodes(graph, harnessNodeId, { allowFiles: true, ...options });
      for (const source of sources) {
        if (source.type !== "file") continue;
        if (typeof source.file !== "string" || !source.file) throw new CanvasGraphError(`File source node "${source.id}" has no file path.`);
        const content = await readFile(source.file);
        if (typeof content !== "string") throw new CanvasGraphError(`File source node "${source.id}" could not be read.`);
        source.content = content;
        source.title = sourceTitle({ id: source.file, text: content }) || path2.basename(source.file);
      }
      return sources;
    }
    function buildCanvasContextContent(sources) {
      if (!Array.isArray(sources) || sources.length === 0) throw new CanvasGraphError("No incoming Canvas nodes are connected to this Pi harness.");
      const sections = ["The following content is the current context of this Obsidian Canvas harness, connected to it by the user."];
      const sourceNodes = sources.map((source) => ({
        id: source.id,
        type: source.type,
        title: source.title,
        contentHash: sha256(source.content)
      }));
      for (const source of sources) {
        sections.push(`## Source: ${source.title}

Canvas node: \`${source.id}\`

${source.content}`);
      }
      sections.push("## Instructions\n\nTreat the sections above as reference material supplied by the user.");
      return { content: sections.join("\n\n"), sourceNodes };
    }
    function contextFingerprint(graph) {
      const nodes = graph.nodes.map(canonicalize).sort(compareCanvasItems);
      const edges = graph.edges.map(canonicalize).sort(compareCanvasItems);
      return sha256(JSON.stringify({ nodes, edges }));
    }
    function canonicalize(value) {
      if (Array.isArray(value)) return value.map(canonicalize);
      if (!value || typeof value !== "object") return value;
      return Object.keys(value).sort().reduce((result, key) => {
        result[key] = canonicalize(value[key]);
        return result;
      }, {});
    }
    function compareCanvasItems(left, right) {
      return JSON.stringify(left).localeCompare(JSON.stringify(right));
    }
    function sourceTitle(source) {
      const firstLine = source.text.split(/\r?\n/).find((line) => line.trim());
      if (!firstLine) return source.id;
      const title = firstLine.replace(/^\s*#{1,6}\s+/, "").trim();
      return title || source.id;
    }
    function sha256(content) {
      return `sha256:${crypto.createHash("sha256").update(content).digest("hex")}`;
    }
    module2.exports = { CanvasGraphError, buildCanvasContextContent, buildConnections, contextFingerprint, getIncomingSourceNodes, getOutgoingTargets, parseCanvasGraph, resolveIncomingSourceNodes, resolveOutgoingTarget };
  }
});

// src/canvas-writer.js
var require_canvas_writer = __commonJS({
  "src/canvas-writer.js"(exports2, module2) {
    "use strict";
    var { CanvasGraphError, parseCanvasGraph, resolveOutgoingTarget } = require_canvas_graph();
    var mutationQueues = /* @__PURE__ */ new Map();
    function appendContent(existing, content) {
      if (!existing) return content;
      if (!content) return existing;
      return existing.endsWith("\n") ? `${existing}${content}` : `${existing}
${content}`;
    }
    function applyMode(existing, content, mode) {
      if (mode === "replace") return content;
      if (mode === "append") return appendContent(existing, content);
      throw new CanvasGraphError(`Unsupported write mode "${mode}".`);
    }
    function enqueue(key, operation) {
      const previous = mutationQueues.get(key) || Promise.resolve();
      const current = previous.catch(() => {
      }).then(operation);
      const settled = current.catch(() => {
      }).finally(() => {
        if (mutationQueues.get(key) === settled) mutationQueues.delete(key);
      });
      mutationQueues.set(key, settled);
      return current;
    }
    async function writeCanvasOrVaultTarget({ vault, canvasFile, harnessNodeId, targetNodeId, content, mode = "replace" }) {
      if (!vault || !canvasFile) throw new CanvasGraphError("Canvas writer requires a vault and Canvas file.");
      if (typeof content !== "string") throw new CanvasGraphError("Canvas write content must be a string.");
      return enqueue(canvasFile.path, async () => {
        const graph = parseCanvasGraph(await vault.cachedRead(canvasFile));
        const target = resolveOutgoingTarget(graph, harnessNodeId, targetNodeId);
        if (target.type === "text") {
          await vault.process(canvasFile, (current) => {
            const liveGraph = parseCanvasGraph(current);
            const liveTarget = resolveOutgoingTarget(liveGraph, harnessNodeId, targetNodeId);
            const node = liveGraph.nodes.find((candidate) => candidate.id === liveTarget.id);
            node.text = applyMode(node.text, content, mode);
            return `${JSON.stringify(liveGraph, null, 2)}
`;
          });
          return { targetNodeId: target.id, targetType: target.type, mode };
        }
        const file = vault.getAbstractFileByPath(target.file);
        if (!file) throw new CanvasGraphError(`Referenced Canvas file "${target.file}" was not found in the vault.`);
        await vault.process(file, (current) => applyMode(current, content, mode));
        return { targetNodeId: target.id, targetType: target.type, file: target.file, mode };
      });
    }
    module2.exports = { appendContent, applyMode, writeCanvasOrVaultTarget };
  }
});

// src/harness-session.js
var require_harness_session = __commonJS({
  "src/harness-session.js"(exports2, module2) {
    "use strict";
    var fsp = require("fs/promises");
    var path2 = require("path");
    var { TFile: TFile2 } = require("obsidian");
    var { validateCanvasWriteOperation, writeCanvasWriteAcknowledgement } = require_harness_transport();
    var { contextFingerprint, parseCanvasGraph } = require_canvas_graph();
    var { TerminalSession } = require_terminal_session();
    var { writeCanvasOrVaultTarget } = require_canvas_writer();
    var HarnessSession = class {
      constructor({ plugin, provider, bridge, terminal, key, harnessId, canvasPath, harnessNodeId }) {
        this.plugin = plugin;
        this.provider = provider;
        this.bridge = bridge;
        this.terminal = terminal;
        this.key = key;
        this.harnessId = harnessId;
        this.canvasPath = canvasPath;
        this.harnessNodeId = harnessNodeId;
        this.contextVersion = null;
        this.stateSync = Promise.resolve();
        this.writeProcessing = Promise.resolve();
        this.writeTimer = null;
        this.onDispose = null;
        this.disposed = false;
      }
      start() {
        this.writeTimer = setInterval(() => {
          this.writeProcessing = this.writeProcessing.then(() => this.processWrites()).catch(() => {
          });
        }, 100);
        this.writeProcessing = this.writeProcessing.then(() => this.processWrites()).catch(() => {
        });
        return this.terminal;
      }
      /**
       * Mirrors the live Canvas graph for the Pi side tools. No node content is resolved, staged,
       * or pushed here: `read_context` reads the graph and the vault itself when the model asks.
       */
      syncState(graph) {
        this.stateSync = this.stateSync.catch(() => {
        }).then(async () => {
          if (this.disposed) return;
          const contextVersion = contextFingerprint(graph);
          if (this.contextVersion === contextVersion) return;
          await writeJsonAtomically(this.bridge.canvasStatePath, {
            protocolVersion: this.bridge.protocolVersion,
            harnessId: this.harnessId,
            canvasPath: this.canvasPath,
            harnessNodeId: this.harnessNodeId,
            contextVersion,
            capturedAt: (/* @__PURE__ */ new Date()).toISOString(),
            graph: { nodes: graph.nodes, edges: graph.edges }
          });
          this.contextVersion = contextVersion;
        });
        return this.stateSync;
      }
      async processWrites() {
        if (this.disposed) return;
        let names;
        try {
          names = (await fsp.readdir(this.bridge.outboxDirectory)).filter((name) => name.endsWith(".json")).sort();
        } catch {
          return;
        }
        for (const name of names) await this.processWrite(path2.join(this.bridge.outboxDirectory, name), name);
      }
      async processWrite(operationPath, name) {
        let operation;
        try {
          operation = JSON.parse(await fsp.readFile(operationPath, "utf8"));
          validateCanvasWriteOperation(operation, { harnessId: this.harnessId, bridgeToken: this.bridge.bridgeToken });
          if (operation.canvasPath !== this.canvasPath) throw new Error("Canvas operation does not match the active harness session.");
          if (operation.harnessNodeId !== this.harnessNodeId) throw new Error("Canvas operation targets a different harness node.");
          const canvasFile = this.plugin.app.vault.getAbstractFileByPath(this.canvasPath);
          if (!(canvasFile instanceof TFile2)) throw new Error(`Canvas file "${this.canvasPath}" was not found.`);
          const result = await writeCanvasOrVaultTarget({
            vault: this.plugin.app.vault,
            canvasFile,
            harnessNodeId: this.harnessNodeId,
            targetNodeId: operation.targetNodeId,
            content: operation.content,
            mode: operation.mode
          });
          await this.writeAcknowledgement(operation, { status: "accepted", ...result });
          await this.move(operationPath, path2.join(this.bridge.writeProcessedDirectory, name));
        } catch (error) {
          const operationId = operation?.operationId || path2.basename(name, ".json");
          if (!operationId.startsWith("write-")) return;
          await this.writeAcknowledgement({ operationId }, { status: "rejected", error: error.message });
          await this.move(operationPath, path2.join(this.bridge.writeErrorsDirectory, name));
        }
      }
      async writeAcknowledgement(operation, result) {
        await writeCanvasWriteAcknowledgement(this.bridge, {
          version: this.bridge.protocolVersion,
          operationId: operation.operationId,
          harnessId: this.harnessId,
          receivedAt: (/* @__PURE__ */ new Date()).toISOString(),
          ...result
        });
      }
      async move(from, to) {
        try {
          await fsp.rename(from, to);
        } catch (error) {
          if (error.code !== "ENOENT") throw error;
        }
      }
      dispose() {
        if (this.disposed) return;
        this.disposed = true;
        if (this.writeTimer) clearInterval(this.writeTimer);
        if (this.onDispose) this.onDispose(this);
        this.terminal.dispose();
        void fsp.rm(this.bridge.directory, { recursive: true, force: true });
      }
    };
    async function createHarnessSession({ plugin, provider, bridge, graph, key, harnessId, canvasPath, harnessNodeId }) {
      const file = plugin.app.vault.getAbstractFileByPath(canvasPath);
      if (!(file instanceof TFile2)) throw new Error(`Canvas file "${canvasPath}" was not found in the vault.`);
      const canvasGraph = graph || parseCanvasGraph(await plugin.app.vault.cachedRead(file));
      const launch = provider.createLaunchSpec({ bridge, vaultPath: plugin.getVaultPath() });
      const terminal = new TerminalSession(plugin, launch);
      const session = new HarnessSession({ plugin, provider, bridge, terminal, key, harnessId, canvasPath, harnessNodeId });
      await session.syncState(canvasGraph);
      terminal.onDispose = () => session.dispose();
      bridge.session = session;
      return session;
    }
    async function writeJsonAtomically(filePath, value) {
      const temporaryPath = `${filePath}.${process.pid}.${Date.now()}.tmp`;
      await fsp.writeFile(temporaryPath, `${JSON.stringify(value)}
`, { encoding: "utf8", mode: 384 });
      await fsp.rename(temporaryPath, filePath);
    }
    module2.exports = { HarnessSession, createHarnessSession };
  }
});

// src/harness-manager.js
var require_harness_manager = __commonJS({
  "src/harness-manager.js"(exports2, module2) {
    "use strict";
    var fsp = require("fs/promises");
    var { TFile: TFile2 } = require("obsidian");
    var { createBridgeSession } = require_harness_transport();
    var { findDuplicateHarnessIds, parseHarnessNode, parseHarnessSource } = require_pi_harness();
    var { createHarnessSession } = require_harness_session();
    var { liveCanvasContent, openCanvasPaths } = require_canvas();
    var { parseCanvasGraph } = require_canvas_graph();
    var SAVE_SYNC_DEBOUNCE_MS = 750;
    var LIVE_MIRROR_INTERVAL_MS = 250;
    var HarnessManager2 = class {
      constructor(plugin, providers) {
        this.plugin = plugin;
        this.providers = providers;
        this.sessions = /* @__PURE__ */ new Map();
        this.syncTimers = /* @__PURE__ */ new Map();
        this.liveMirrorTimers = /* @__PURE__ */ new Map();
      }
      key(canvasPath, nodeId) {
        return `${canvasPath}:${nodeId}`;
      }
      async create(source, sourcePath) {
        const declaration = parseHarnessSource(source);
        if (!declaration.valid) {
          this.plugin.notify(`Invalid harness: ${declaration.errors.join(" ")}`);
          return null;
        }
        const provider = this.providers.get(declaration.harness.agent);
        if (!provider) {
          this.plugin.notify(`Unsupported harness provider "${declaration.harness.agent}".`);
          return null;
        }
        const candidates = canvasCandidates(sourcePath, openCanvasPaths(this.plugin.app));
        const located = await this.locate(candidates, declaration.harness.id);
        if (!located) {
          this.plugin.notify(`Could not uniquely identify harness "${declaration.harness.id}" in ${candidates[0] || "an open Canvas"}.`);
          return null;
        }
        const { canvasPath, harnessNodeId, graph } = located;
        const key = this.key(canvasPath, harnessNodeId);
        const existing = this.sessions.get(key);
        if (existing && !existing.disposed) return existing.terminal;
        const bridge = await createBridgeSession();
        bridge.harnessId = declaration.harness.id;
        bridge.canvasPath = canvasPath;
        bridge.harnessNodeId = harnessNodeId;
        let session;
        try {
          session = await createHarnessSession({
            plugin: this.plugin,
            provider,
            bridge,
            graph,
            key,
            harnessId: declaration.harness.id,
            canvasPath,
            harnessNodeId
          });
        } catch (error) {
          await fsp.rm(bridge.directory, { recursive: true, force: true }).catch(() => {
          });
          this.plugin.notify(`Could not start harness "${declaration.harness.id}": ${error.message}`);
          return null;
        }
        session.onDispose = () => this.remove(session);
        this.sessions.set(key, session);
        this.startLiveMirror(canvasPath);
        session.start();
        return session.terminal;
      }
      scheduleSync(file) {
        if (!(file instanceof TFile2) || file.extension !== "canvas") return;
        clearTimeout(this.syncTimers.get(file.path));
        this.syncTimers.set(file.path, setTimeout(() => {
          this.syncTimers.delete(file.path);
          void this.mirror(file.path, { notify: true });
        }, SAVE_SYNC_DEBOUNCE_MS));
      }
      /**
       * Obsidian's vault modify event only observes saved Canvas data. Poll the live Canvas document
       * while a harness is open so unsaved card and edge edits reach Pi as well.
       */
      startLiveMirror(canvasPath) {
        if (this.liveMirrorTimers.has(canvasPath)) return;
        this.liveMirrorTimers.set(canvasPath, setInterval(() => {
          void this.mirror(canvasPath);
        }, LIVE_MIRROR_INTERVAL_MS));
      }
      /** Writes the current Canvas graph into every live harness session on that Canvas. */
      async mirror(canvasPath, { notify = false } = {}) {
        let graph;
        try {
          graph = (await this.canvasGraphs(canvasPath))[0];
          if (!graph || findDuplicateHarnessIds(graph.nodes).length) return;
        } catch {
          return;
        }
        for (const node of graph.nodes.filter((candidate) => candidate.type === "text")) {
          const declaration = parseHarnessNode(node.text);
          if (!declaration.valid) continue;
          const session = this.sessions.get(this.key(canvasPath, node.id));
          if (!session) continue;
          try {
            await session.syncState(graph);
          } catch (error) {
            if (notify) this.plugin.notify(`Could not refresh Canvas state for ${declaration.harness.id}: ${error.message}`);
          }
        }
      }
      /** First candidate Canvas that holds exactly one node declaring the harness. */
      async locate(canvasPaths, harnessId) {
        for (const canvasPath of canvasPaths) {
          for (const graph of await this.canvasGraphs(canvasPath)) {
            const matches = graph.nodes.filter((node) => node.type === "text" && parseHarnessNode(node.text).harness?.id === harnessId);
            if (matches.length === 1) return { canvasPath, harnessNodeId: matches[0].id, graph };
            if (matches.length > 1) return null;
          }
        }
        return null;
      }
      /**
       * A Canvas code block has no source path and a card Obsidian created moments ago may not be
       * in the saved file yet, so the live Canvas document is searched before the file on disk.
       */
      async canvasGraphs(canvasPath) {
        const contents = [liveCanvasContent(this.plugin.app, canvasPath)];
        const file = this.plugin.app.vault.getAbstractFileByPath(canvasPath);
        if (file instanceof TFile2) contents.push(await this.plugin.app.vault.cachedRead(file));
        return contents.filter(Boolean).map((content) => parseCanvasGraph(content));
      }
      remove(session) {
        if (this.sessions.get(session.key) !== session) return;
        this.sessions.delete(session.key);
        if (![...this.sessions.values()].some((candidate) => candidate.canvasPath === session.canvasPath)) {
          clearInterval(this.liveMirrorTimers.get(session.canvasPath));
          this.liveMirrorTimers.delete(session.canvasPath);
        }
      }
      dispose() {
        for (const timer of this.syncTimers.values()) clearTimeout(timer);
        this.syncTimers.clear();
        for (const timer of this.liveMirrorTimers.values()) clearInterval(timer);
        this.liveMirrorTimers.clear();
        for (const session of this.sessions.values()) session.dispose();
        this.sessions.clear();
      }
    };
    function canvasCandidates(sourcePath, openPaths) {
      const paths = [];
      for (const candidate of [sourcePath, ...openPaths]) {
        if (typeof candidate === "string" && candidate.endsWith(".canvas") && !paths.includes(candidate)) paths.push(candidate);
      }
      return paths;
    }
    module2.exports = { HarnessManager: HarnessManager2 };
  }
});

// src/research-partner-prompt.js
var require_research_partner_prompt = __commonJS({
  "src/research-partner-prompt.js"(exports2, module2) {
    "use strict";
    var RESEARCH_PARTNER_PROMPT = `# Research Partner

## Posture

You are a research partner. Your job is to investigate, understand, and decide with the
user, not to close tickets. Read files, run commands, and search sources freely: reading
is research.

## Canvas protocol

This session is bound to an Obsidian Canvas. The material you must work with lives in the
nodes connected TO this harness, not in the user's message.

- \`read_context\` returns every node connected by an incoming edge. Call it before you
  reason about any request in this session. Nodes this harness points at are outputs, not
  context.
- \`find_connected_nodes\` lists direct connections with their direction and node IDs. Call
  it before writing when the target ID is unknown.
- \`write_canvas_node\` writes to one direct outgoing node. Name the target explicitly.
  Never guess a target, never fan out, never use it for unrelated files. \`replace\` is the
  default mode; \`append\` adds a newline boundary.
- Do not read the Canvas document from disk. It is live in Obsidian and the file can be
  stale. Use \`read_context\`.

## Method

1. Frame the question in your own words and name what a good answer would contain. If it
   is underspecified, say what you would need first.
2. Gather before concluding. Prefer primary sources over memory: the Canvas nodes, the
   vault, the repository, the live system. State which you actually consulted.
3. Synthesize: the answer, the evidence, the open questions. Do not restate sources at
   length.
4. Challenge the framing. If it embeds an assumption that looks wrong, say so and explain
   what changes if it is wrong. Test the plan, not only the facts.
5. Separate what is established, what is inferred, and what is unknown.

## Evidence

- Mark provenance for every claim the reader could not derive themselves: source, date,
  and whether it is verbatim, compiled, or your inference.
- Never present recollection as evidence. If you cannot verify a claim, label it
  unverified or say you do not know.
- When sources conflict, surface the conflict. Do not silently pick one.
- Name what would resolve an open question.

## Disagreement

Be a colleague, not a mirror. If the position is sound, say so briefly and move on. If it
is not, state that first, then the reason, then the alternative. Never manufacture
objections to appear rigorous: disagree only when you can point at the specific thing
that is wrong.

## Uncertainty

Say "I don't know" plainly. Distinguish "no evidence found" from "evidence says no".
Do not pad an answer to appear complete.

## Output

- Lead with the answer. Fit the whole thing on one screen when the material allows.
- Prose for reasoning; tables, lists, and diagrams for structure, comparison, and flow.
- For long material, show a small representative part, say what the rest contains, and ask
  whether to continue.
- No em dashes. No filler openers. No mannered flourishes.
- Never omit material facts to stay short. Summarize, then offer the detail.

## Boundaries

- Only the three Canvas tools may write. Do not invent file paths, endpoints, or APIs.
  Verify, or say you are guessing.
`;
    module2.exports = { RESEARCH_PARTNER_PROMPT };
  }
});

// src/harness-provider.js
var require_harness_provider = __commonJS({
  "src/harness-provider.js"(exports2, module2) {
    "use strict";
    var crypto = require("crypto");
    var path2 = require("path");
    var { RESEARCH_PARTNER_PROMPT } = require_research_partner_prompt();
    var PiHarnessProvider2 = class {
      constructor(plugin) {
        this.id = "pi";
        this.plugin = plugin;
      }
      createLaunchSpec({ bridge, vaultPath }) {
        const bridgeExtensionPath = path2.join(this.plugin.pluginDir(), "bridge", "open-terminal-canvas.js");
        const executable = this.plugin.settings.harnessProviders?.pi?.executable?.trim() || "pi";
        const env = {
          OPEN_TERMINAL_VAULT_ID: crypto.createHash("sha256").update(vaultPath).digest("hex"),
          OPEN_TERMINAL_HARNESS_ID: bridge.harnessId,
          OPEN_TERMINAL_BRIDGE_DIR: bridge.directory,
          OPEN_TERMINAL_BRIDGE_TOKEN: bridge.bridgeToken,
          OPEN_TERMINAL_PROTOCOL_VERSION: String(bridge.protocolVersion),
          OPEN_TERMINAL_CANVAS_PATH: bridge.canvasPath || "",
          OPEN_TERMINAL_HARNESS_NODE_ID: bridge.harnessNodeId || "",
          OPEN_TERMINAL_CANVAS_STATE_PATH: bridge.canvasStatePath || ""
        };
        return {
          cwd: vaultPath,
          command: `${this.plugin.quoteArg(executable)} --extension ${this.plugin.quoteArg(bridgeExtensionPath)} --exclude-tools edit,write --system-prompt ${this.plugin.quoteArg(RESEARCH_PARTNER_PROMPT)}`,
          env
        };
      }
    };
    var HarnessProviderRegistry2 = class {
      constructor(providers) {
        this.providers = new Map(providers.map((provider) => [provider.id, provider]));
      }
      get(id) {
        return this.providers.get(id) || null;
      }
    };
    module2.exports = { HarnessProviderRegistry: HarnessProviderRegistry2, PiHarnessProvider: PiHarnessProvider2 };
  }
});

// src/main.js
var { Plugin, Notice, FileSystemAdapter, TFile, TFolder } = require("obsidian");
var path = require("path");
var { VIEW_TYPE, BLOCK_LANG, DEFAULT_SETTINGS } = require_constants();
var shell = require_shell();
var { TerminalView } = require_terminal_view();
var { BlockSessions, blockKey, newBlockMarkdown } = require_block_sessions();
var { getActiveCanvas, addPiHarnessToCanvas, addTerminalToCanvas } = require_canvas();
var { OpenTerminalSettingTab } = require_settings_tab();
var { HarnessManager } = require_harness_manager();
var { HarnessProviderRegistry, PiHarnessProvider } = require_harness_provider();
var { GENERIC_HARNESS_LANGUAGE, HARNESS_LANGUAGE } = require_pi_harness();
var OpenTerminalPlugin = class extends Plugin {
  async onload() {
    await this.loadSettings();
    this.harnessLanguage = HARNESS_LANGUAGE;
    this.harnesses = new HarnessManager(this, new HarnessProviderRegistry([
      new PiHarnessProvider(this)
    ]));
    this.registerEvent(this.app.vault.on("modify", (file) => this.harnesses.scheduleSync(file)));
    this.registerView(VIEW_TYPE, (leaf) => new TerminalView(leaf, this));
    this.addRibbonIcon("terminal-square", "Open terminal", () => this.openTerminal(this.getVaultPath()));
    this.addCommand({
      id: "open-terminal-vault",
      name: "Open terminal at vault root",
      callback: () => this.openTerminal(this.getVaultPath())
    });
    this.addCommand({
      id: "open-terminal-current-folder",
      name: "Open terminal at current note's folder",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file) return false;
        if (!checking) this.openTerminal(this.getAbsolutePath(file.parent));
        return true;
      }
    });
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => {
      const folder = file instanceof TFolder ? file : file instanceof TFile ? file.parent : null;
      if (!folder) return;
      menu.addItem((item) => item.setTitle("Open in terminal").setIcon("terminal-square").onClick(() => this.openTerminal(this.getAbsolutePath(folder))));
      if (!(file instanceof TFile) || file.extension !== "canvas") return;
      menu.addItem((item) => item.setTitle("Add harness").setIcon("bot").onClick(async () => {
        await this.app.workspace.getLeaf(false).openFile(file);
        const canvas = getActiveCanvas(this.app);
        if (canvas) addPiHarnessToCanvas(canvas);
      }));
    }));
    this.registerEvent(this.app.workspace.on("canvas-menu", (menu, canvas) => {
      const targetCanvas = canvas || getActiveCanvas(this.app);
      if (!targetCanvas) return;
      menu.addItem((item) => item.setTitle("Add harness").setIcon("bot").onClick(() => addPiHarnessToCanvas(targetCanvas)));
    }));
    this.blocks = new BlockSessions(this);
    this.registerMarkdownCodeBlockProcessor(BLOCK_LANG, (source, el, ctx) => this.blocks.process(source, el, ctx));
    this.piHarnessBlocks = new BlockSessions(this, {
      language: [HARNESS_LANGUAGE, GENERIC_HARNESS_LANGUAGE],
      keyFor: (source, sourcePath) => `${sourcePath}::${blockKey(source, sourcePath)}`,
      createSession: (_opts, ctx, source) => this.harnesses.create(source, ctx.sourcePath)
    });
    this.registerMarkdownCodeBlockProcessor(HARNESS_LANGUAGE, (source, el, ctx) => this.piHarnessBlocks.process(source, el, ctx));
    this.registerMarkdownCodeBlockProcessor(GENERIC_HARNESS_LANGUAGE, (source, el, ctx) => this.piHarnessBlocks.process(source, el, ctx));
    this.addCommand({
      id: "insert-terminal-block",
      name: "Insert terminal into note",
      editorCallback: (editor) => editor.replaceSelection(newBlockMarkdown() + "\n")
    });
    this.addCommand({
      id: "add-terminal-to-canvas",
      name: "Add terminal to canvas",
      checkCallback: (checking) => {
        const canvas = getActiveCanvas(this.app);
        if (!canvas) return false;
        if (!checking) addTerminalToCanvas(canvas);
        return true;
      }
    });
    this.addCommand({
      id: "create-pi-harness-on-canvas",
      name: "Create Pi harness on Canvas",
      checkCallback: (checking) => {
        const canvas = getActiveCanvas(this.app);
        if (!canvas) return false;
        if (!checking) addPiHarnessToCanvas(canvas);
        return true;
      }
    });
    this.addSettingTab(new OpenTerminalSettingTab(this.app, this));
  }
  onunload() {
    this.blocks.disposeAll();
    this.piHarnessBlocks.disposeAll();
    this.harnesses.dispose();
  }
  notify(message) {
    new Notice(message);
  }
  async runInTerminal(command, { cwd, reuse = false } = {}) {
    cwd = cwd || this.getVaultPath();
    if (reuse) {
      const view = this.getTerminals().find((candidate) => candidate.isAtPrompt());
      if (view) {
        view.reveal();
        view.sendText(`${this.cdCommand(cwd)} ${this.shellSeparator()} ${command}`);
        return view;
      }
    }
    return this.openTerminal(cwd, command);
  }
  getTerminals() {
    const views = this.app.workspace.getLeavesOfType(VIEW_TYPE).map((leaf) => leaf.view).filter((view) => view instanceof TerminalView).reverse();
    return [...views, ...this.blocks.visible()];
  }
  async openTerminal(cwd, command, env) {
    if (!cwd) {
      this.notify("Could not determine the folder path.");
      return;
    }
    const { workspace } = this;
    let leaf;
    switch (this.settings.location) {
      case "tab":
        leaf = workspace.getLeaf("tab");
        break;
      case "right":
        leaf = workspace.getRightLeaf(false);
        break;
      default:
        leaf = workspace.getLeaf("split", "horizontal");
    }
    await leaf.setViewState({ type: VIEW_TYPE, active: true, state: { cwd, command, env } });
    workspace.revealLeaf(leaf);
    return leaf.view;
  }
  loadXterm() {
    if (!this.xterm) {
      const base = path.join(this.pluginDir(), "node_modules", "@xterm");
      const { Terminal } = window.require(path.join(base, "xterm", "lib", "xterm.js"));
      const { FitAddon } = window.require(path.join(base, "addon-fit", "lib", "addon-fit.js"));
      this.xterm = { Terminal, FitAddon };
    }
    return this.xterm;
  }
  getShell() {
    return shell.getShell(this.settings);
  }
  resolveNodePath() {
    return shell.resolveNodePath(this.settings);
  }
  cdCommand(dir) {
    return shell.cdCommand(this.getShell().cmd, dir);
  }
  shellSeparator() {
    return shell.shellSeparator(this.getShell().cmd);
  }
  quoteArg(arg) {
    return shell.quoteArg(this.getShell().cmd, arg);
  }
  pluginDir() {
    return path.join(this.getVaultPath(), this.manifest.dir);
  }
  hostPath() {
    return path.join(this.pluginDir(), "pty-host.js");
  }
  getVaultPath() {
    const adapter = this.app.vault.adapter;
    return adapter instanceof FileSystemAdapter ? adapter.getBasePath() : null;
  }
  getAbsolutePath(folder) {
    const base = this.getVaultPath();
    if (!base) return null;
    if (!folder || folder.isRoot()) return base;
    return path.join(base, folder.path);
  }
  async loadSettings() {
    const stored = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, stored);
    this.settings.harnessProviders = Object.assign({}, DEFAULT_SETTINGS.harnessProviders, stored?.harnessProviders);
    this.settings.harnessProviders.pi = Object.assign(
      {},
      DEFAULT_SETTINGS.harnessProviders.pi,
      this.settings.harnessProviders.pi,
      stored?.piPath ? { executable: stored.piPath } : {}
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
module.exports = OpenTerminalPlugin;
