/* Generated by esbuild from src/ — edit the files in src/, not this one. */
"use strict";
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/constants.js
var require_constants = __commonJS({
  "src/constants.js"(exports2, module2) {
    "use strict";
    var VIEW_TYPE2 = "open-terminal-view";
    var BLOCK_LANG2 = "terminal";
    var DEFAULT_SETTINGS2 = {
      // "auto", "powershell", "pwsh", "cmd" (Windows), "zsh", "bash" (macOS/Linux) or "custom"
      shell: "auto",
      customShell: "",
      // "bottom" (split panel below), "tab" (new tab) or "right" (right sidebar)
      location: "bottom",
      // Empty = auto-detect
      nodePath: "",
      fontSize: 14
    };
    var SHELLS = {
      powershell: { cmd: "powershell.exe", args: ["-NoLogo"], win: true },
      pwsh: { cmd: "pwsh.exe", args: ["-NoLogo"], win: true },
      cmd: { cmd: "cmd.exe", args: [], win: true },
      zsh: { cmd: "/bin/zsh", args: ["-l"], win: false },
      bash: { cmd: "/bin/bash", args: ["-l"], win: false }
    };
    module2.exports = { VIEW_TYPE: VIEW_TYPE2, BLOCK_LANG: BLOCK_LANG2, DEFAULT_SETTINGS: DEFAULT_SETTINGS2, SHELLS };
  }
});

// src/shell.js
var require_shell = __commonJS({
  "src/shell.js"(exports2, module2) {
    "use strict";
    var fs = require("fs");
    var path2 = require("path");
    var { SHELLS } = require_constants();
    function getShell(settings) {
      if (settings.shell === "custom" && settings.customShell.trim()) {
        const parts = settings.customShell.trim().match(/"[^"]*"|\S+/g).map((p) => p.replace(/^"|"$/g, ""));
        return { cmd: parts[0], args: parts.slice(1) };
      }
      const isWin = process.platform === "win32";
      const picked = SHELLS[settings.shell];
      if (picked && picked.win === isWin) return picked;
      if (isWin) return SHELLS.powershell;
      return { cmd: process.env.SHELL || (process.platform === "darwin" ? "/bin/zsh" : "/bin/bash"), args: ["-l"] };
    }
    function resolveNodePath(settings) {
      if (settings.nodePath.trim()) return settings.nodePath.trim();
      const candidates = [];
      const dirs = (process.env.PATH || "").split(path2.delimiter);
      const exe = process.platform === "win32" ? "node.exe" : "node";
      for (const d of dirs) if (d) candidates.push(path2.join(d, exe));
      if (process.platform === "win32") {
        candidates.push(path2.join(process.env.ProgramFiles || "C:\\Program Files", "nodejs", "node.exe"));
        if (process.env.APPDATA) candidates.push(path2.join(process.env.APPDATA, "nvm", "current", "node.exe"));
      } else {
        candidates.push("/usr/local/bin/node", "/opt/homebrew/bin/node", "/usr/bin/node");
      }
      return candidates.find((c) => fs.existsSync(c)) || null;
    }
    function quoteArg(shellCmd, arg) {
      const shell2 = shellCmd.toLowerCase();
      if (shell2.includes("cmd")) return '"' + String(arg).replace(/"/g, '""') + '"';
      if (shell2.includes("powershell") || shell2.includes("pwsh")) return "'" + String(arg).replace(/'/g, "''") + "'";
      return "'" + String(arg).replace(/'/g, "'\\''") + "'";
    }
    function cdCommand(shellCmd, dir) {
      const shell2 = shellCmd.toLowerCase();
      if (shell2.includes("powershell") || shell2.includes("pwsh")) return `Set-Location -LiteralPath ${quoteArg(shellCmd, dir)}`;
      if (shell2.includes("cmd")) return `cd /d ${quoteArg(shellCmd, dir)}`;
      return `cd ${quoteArg(shellCmd, dir)}`;
    }
    function shellSeparator(shellCmd) {
      return shellCmd.toLowerCase().includes("cmd") ? "&&" : ";";
    }
    module2.exports = { getShell, resolveNodePath, quoteArg, cdCommand, shellSeparator };
  }
});

// src/terminal-session.js
var require_terminal_session = __commonJS({
  "src/terminal-session.js"(exports2, module2) {
    "use strict";
    var { spawn } = require("child_process");
    var TerminalSession = class {
      constructor(plugin, { cwd, command } = {}) {
        this.plugin = plugin;
        this.cwd = cwd;
        this.pendingCommand = command || null;
        this.host = null;
        this.term = null;
        this.fit = null;
        this.exited = false;
        this.disposed = false;
        this.lastActive = Date.now();
        this.parentEl = null;
        this.onReveal = null;
        this.el = createDiv({ cls: "open-terminal-xterm" });
      }
      /** Shows the terminal inside parentEl (creates xterm the first time). */
      attach(parentEl) {
        if (this.disposed) return;
        this.detach();
        this.parentEl = parentEl;
        parentEl.appendChild(this.el);
        if (!this.term) this.createTerm();
        else this.term.refresh(0, this.term.rows - 1);
        this.resizeObserver = new ResizeObserver(() => this.resize());
        this.resizeObserver.observe(parentEl);
        this.resize();
        if (!this.host && !this.exited) this.startShell();
      }
      /** Removes the terminal from the DOM, keeping the shell alive. */
      detach() {
        if (this.resizeObserver) this.resizeObserver.disconnect();
        this.resizeObserver = null;
        this.parentEl = null;
        this.el.detach();
      }
      isAttached() {
        return !!this.parentEl && this.el.isConnected;
      }
      createTerm() {
        const { Terminal, FitAddon } = this.plugin.loadXterm();
        const css = getComputedStyle(document.body);
        const cssVar = (name, fallback) => css.getPropertyValue(name).trim() || fallback;
        this.term = new Terminal({
          cursorBlink: true,
          fontSize: this.plugin.settings.fontSize,
          fontFamily: cssVar("--font-monospace", "Consolas, 'Courier New', monospace"),
          scrollback: 5e3,
          allowProposedApi: true,
          theme: {
            background: cssVar("--background-primary", "#1e1e1e"),
            foreground: cssVar("--text-normal", "#dcddde"),
            cursor: cssVar("--text-accent", "#7f6df2"),
            selectionBackground: cssVar("--text-selection", "rgba(127,109,242,0.35)")
          }
        });
        this.fit = new FitAddon();
        this.term.loadAddon(this.fit);
        this.term.open(this.el);
        this.term.attachCustomKeyEventHandler((e) => {
          if (e.type !== "keydown") return true;
          const key = e.key.toLowerCase();
          if (e.ctrlKey && key === "c" && this.term.hasSelection()) {
            navigator.clipboard.writeText(this.term.getSelection());
            this.term.clearSelection();
            return false;
          }
          if (e.ctrlKey && e.shiftKey && key === "c") return false;
          if (e.ctrlKey && key === "v") {
            e.preventDefault();
            navigator.clipboard.readText().then((text) => this.term && this.term.paste(text));
            return false;
          }
          return true;
        });
        this.term.onData((data) => {
          this.lastActive = Date.now();
          if (this.host) this.send({ t: "i", d: data });
          else if (this.exited) this.startShell();
        });
      }
      startShell() {
        if (!this.term || !this.cwd || this.disposed) return;
        this.exited = false;
        const node = this.plugin.resolveNodePath();
        if (!node) {
          this.term.writeln("\x1B[31mNode.js not found. Set the Node.js path in the plugin settings.\x1B[0m");
          return;
        }
        const { cmd, args } = this.plugin.getShell();
        this.fitNow();
        const hostArgs = [this.plugin.hostPath(), this.cwd, cmd, String(this.term.cols), String(this.term.rows), ...args];
        const host = spawn(node, hostArgs, {
          cwd: this.plugin.pluginDir(),
          windowsHide: true,
          stdio: ["pipe", "pipe", "pipe"]
        });
        this.host = host;
        this.lastSize = null;
        host.stdout.setEncoding("utf8");
        host.stderr.setEncoding("utf8");
        host.stdout.on("data", (d) => {
          if (this.term) this.term.write(d);
          if (this.pendingCommand) {
            const cmd2 = this.pendingCommand;
            this.pendingCommand = null;
            setTimeout(() => this.send({ t: "i", d: cmd2 + "\r" }), 400);
          }
        });
        host.stderr.on("data", (d) => this.term && this.term.write(`\x1B[31m${d.replace(/\n/g, "\r\n")}\x1B[0m`));
        host.on("error", (err) => {
          this.term && this.term.writeln(`\x1B[31mFailed to start the terminal: ${err.message}\x1B[0m`);
        });
        host.on("exit", () => {
          if (this.host !== host) return;
          this.host = null;
          this.exited = true;
          if (this.term) this.term.write("\r\n\x1B[2m[process exited \u2014 press any key to restart]\x1B[0m\r\n");
        });
      }
      send(msg) {
        if (this.host && this.host.stdin.writable) this.host.stdin.write(JSON.stringify(msg) + "\n");
      }
      /** Stops the shell (the terminal stays visible and restarts on the next key press). */
      kill() {
        const host = this.host;
        if (!host) return;
        this.send({ t: "k" });
        setTimeout(() => {
          try {
            host.kill();
          } catch {
          }
        }, 1e3);
      }
      /** Restarts the shell in the same folder. */
      restart() {
        const host = this.host;
        if (host) {
          this.host = null;
          try {
            host.kill();
          } catch {
          }
        }
        if (this.term) this.term.reset();
        this.startShell();
      }
      /** Is the shell running (process alive)? */
      isAlive() {
        return !!this.host && !!this.term;
      }
      /** Text of the cursor's line, up to the cursor position. */
      cursorLineText() {
        if (!this.term) return "";
        const b = this.term.buffer.active;
        const line = b.getLine(b.baseY + b.cursorY);
        return line ? line.translateToString(true, 0, b.cursorX) : "";
      }
      /** Is the shell idle at its prompt (no program running)? */
      isAtPrompt() {
        if (!this.isAlive() || this.pendingCommand) return false;
        const text = this.cursorLineText().trimEnd();
        return /^PS [^>]*>$/.test(text) || /^[A-Za-z]:\\[^>]*>$/.test(text) || /[$#%]$/.test(text);
      }
      /** Types text into the terminal; submit=true presses Enter. */
      sendText(text, { submit = true } = {}) {
        this.lastActive = Date.now();
        this.send({ t: "i", d: text });
        if (submit) setTimeout(() => this.send({ t: "i", d: "\r" }), 150);
      }
      reveal() {
        if (this.onReveal) this.onReveal();
        this.focus();
      }
      focus() {
        if (this.term) this.term.focus();
      }
      fitNow() {
        if (!this.fit || !this.el.isShown()) return;
        try {
          this.fit.fit();
        } catch {
        }
      }
      resize() {
        if (!this.term) return;
        const { cols, rows } = this.term;
        this.fitNow();
        if (this.term.cols !== cols || this.term.rows !== rows || !this.lastSize) {
          this.lastSize = true;
          this.send({ t: "r", c: this.term.cols, r: this.term.rows });
        }
      }
      dispose() {
        if (this.disposed) return;
        this.disposed = true;
        this.detach();
        this.kill();
        this.host = null;
        if (this.term) {
          this.term.dispose();
          this.term = null;
        }
      }
    };
    module2.exports = { TerminalSession };
  }
});

// src/terminal-view.js
var require_terminal_view = __commonJS({
  "src/terminal-view.js"(exports2, module2) {
    "use strict";
    var { ItemView } = require("obsidian");
    var path2 = require("path");
    var { VIEW_TYPE: VIEW_TYPE2 } = require_constants();
    var { TerminalSession } = require_terminal_session();
    var TerminalView2 = class extends ItemView {
      constructor(leaf, plugin) {
        super(leaf);
        this.plugin = plugin;
        this.cwd = null;
        this.session = null;
      }
      getViewType() {
        return VIEW_TYPE2;
      }
      getDisplayText() {
        return this.cwd ? `Terminal: ${path2.basename(this.cwd)}` : "Terminal";
      }
      getIcon() {
        return "terminal-square";
      }
      getState() {
        return { cwd: this.cwd };
      }
      async setState(state, result) {
        if (state && state.cwd && !this.session) this.startSession(state.cwd, state.command);
        await super.setState(state, result);
      }
      async onOpen() {
        this.contentEl.empty();
        this.contentEl.addClass("open-terminal-container");
        setTimeout(() => {
          if (!this.session) this.startSession(this.plugin.getVaultPath());
        }, 150);
      }
      startSession(cwd, command) {
        if (!cwd) return;
        this.cwd = cwd;
        this.session = new TerminalSession(this.plugin, { cwd, command });
        this.session.onReveal = () => {
          this.app.workspace.revealLeaf(this.leaf);
          this.app.workspace.setActiveLeaf(this.leaf, { focus: true });
        };
        this.session.attach(this.contentEl);
        this.leaf.updateHeader && this.leaf.updateHeader();
        this.session.focus();
      }
      // Kept for compatibility with code that uses the view directly
      isAlive() {
        return !!this.session && this.session.isAlive();
      }
      isAtPrompt() {
        return !!this.session && this.session.isAtPrompt();
      }
      sendText(text, opts) {
        if (this.session) this.session.sendText(text, opts);
      }
      reveal() {
        if (this.session) this.session.reveal();
      }
      onResize() {
        if (this.session) this.session.resize();
      }
      async onClose() {
        if (this.session) {
          this.session.dispose();
          this.session = null;
        }
      }
    };
    module2.exports = { TerminalView: TerminalView2 };
  }
});

// src/terminal-block.js
var require_terminal_block = __commonJS({
  "src/terminal-block.js"(exports2, module2) {
    "use strict";
    var { MarkdownRenderChild, setIcon } = require("obsidian");
    var path2 = require("path");
    var TerminalBlockChild = class extends MarkdownRenderChild {
      constructor(el, blocks, session, key, sourcePath) {
        super(el);
        this.blocks = blocks;
        this.session = session;
        this.key = key;
        this.sourcePath = sourcePath;
      }
      onload() {
        const el = this.containerEl;
        el.empty();
        el.addClass("open-terminal-block");
        const toolbar = el.createDiv({ cls: "open-terminal-block-toolbar" });
        setIcon(toolbar.createSpan({ cls: "open-terminal-block-icon" }), "terminal-square");
        toolbar.createSpan({ cls: "open-terminal-block-title", text: path2.basename(this.session.cwd || "") || "Terminal" });
        toolbar.setAttr("title", this.session.cwd || "");
        const button = (icon, label, onClick) => {
          const b = toolbar.createEl("button", { cls: "clickable-icon open-terminal-block-button", attr: { "aria-label": label } });
          setIcon(b, icon);
          this.registerDomEvent(b, "click", (e) => {
            e.stopPropagation();
            onClick();
          });
        };
        button("rotate-ccw", "Restart terminal", () => this.session.restart());
        button("square", "Stop process", () => this.session.kill());
        this.body = el.createDiv({ cls: "open-terminal-block-body" });
        for (const ev of ["pointerdown", "mousedown", "click", "dblclick", "wheel", "keydown", "keyup", "contextmenu"]) {
          this.registerDomEvent(this.body, ev, (e) => e.stopPropagation());
        }
        this.session.onReveal = () => el.scrollIntoView({ block: "nearest" });
        whenConnected(el, () => {
          if (this.unloaded) return;
          this.fitToCanvasNode();
          this.session.attach(this.body);
        });
      }
      /** In Canvas, makes the terminal fill the card's full height. */
      fitToCanvasNode() {
        const nodeEl = this.containerEl.closest(".canvas-node-content");
        if (!nodeEl) return;
        this.containerEl.addClass("is-canvas");
        const apply = () => this.containerEl.style.height = `${nodeEl.clientHeight}px`;
        apply();
        this.nodeObserver = new ResizeObserver(apply);
        this.nodeObserver.observe(nodeEl);
      }
      onunload() {
        this.unloaded = true;
        if (this.nodeObserver) this.nodeObserver.disconnect();
        if (this.session.parentEl === this.body) this.session.detach();
        this.blocks.scheduleOrphanCheck(this.key, this.sourcePath);
      }
    };
    function whenConnected(el, cb, tries = 120) {
      if (el.isConnected) return cb();
      if (tries <= 0) return;
      requestAnimationFrame(() => whenConnected(el, cb, tries - 1));
    }
    module2.exports = { TerminalBlockChild };
  }
});

// src/block-sessions.js
var require_block_sessions = __commonJS({
  "src/block-sessions.js"(exports2, module2) {
    "use strict";
    var { TFile: TFile2 } = require("obsidian");
    var path2 = require("path");
    var { BLOCK_LANG: BLOCK_LANG2 } = require_constants();
    var { TerminalSession } = require_terminal_session();
    var { TerminalBlockChild } = require_terminal_block();
    function parseBlockOptions(source) {
      const opts = {};
      for (const line of source.split(/\r?\n/)) {
        const m = line.match(/^\s*([A-Za-z]+)\s*:\s*(.*?)\s*$/);
        if (m) opts[m[1].toLowerCase()] = m[2];
      }
      return opts;
    }
    function blockKey(source, sourcePath) {
      const { id } = parseBlockOptions(source);
      return id ? `id:${id}` : `${sourcePath}::${source.trim()}`;
    }
    function newBlockId() {
      return Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
    }
    function newBlockMarkdown2() {
      return "```" + BLOCK_LANG2 + "\nid: " + newBlockId() + "\n```";
    }
    var BlockSessions2 = class {
      constructor(plugin) {
        this.plugin = plugin;
        this.sessions = /* @__PURE__ */ new Map();
        this.orphanTimers = /* @__PURE__ */ new Map();
      }
      /** Markdown code block processor for ```terminal. */
      process(source, el, ctx) {
        const opts = parseBlockOptions(source);
        const key = blockKey(source, ctx.sourcePath);
        let session = this.sessions.get(key);
        if (!session || session.disposed) {
          session = new TerminalSession(this.plugin, {
            cwd: this.resolveCwd(opts.cwd, ctx.sourcePath),
            command: opts.command
          });
          this.sessions.set(key, session);
        }
        ctx.addChild(new TerminalBlockChild(el, this, session, key, ctx.sourcePath));
      }
      /** Block cwd: absolute, relative to the vault root, or (default) the folder of the file containing the block. */
      resolveCwd(cwd, sourcePath) {
        const vault = this.plugin.getVaultPath();
        if (cwd) return path2.isAbsolute(cwd) ? cwd : path2.join(vault, cwd);
        const file = this.plugin.app.vault.getAbstractFileByPath(sourcePath);
        return file instanceof TFile2 ? this.plugin.getAbsolutePath(file.parent) : vault;
      }
      /** Sessions currently shown on screen, most recently used first. */
      visible() {
        return [...this.sessions.values()].filter((s) => !s.disposed && s.isAttached()).sort((a, b) => b.lastActive - a.lastActive);
      }
      /**
       * Called when a block leaves the DOM. Canvas unloads off-screen cards,
       * so the shell is only stopped if the block no longer exists in the file.
       */
      scheduleOrphanCheck(key, sourcePath) {
        clearTimeout(this.orphanTimers.get(key));
        this.orphanTimers.set(
          key,
          setTimeout(async () => {
            this.orphanTimers.delete(key);
            const session = this.sessions.get(key);
            if (!session || session.isAttached()) return;
            const file = this.plugin.app.vault.getAbstractFileByPath(sourcePath);
            let keys = /* @__PURE__ */ new Set();
            if (file instanceof TFile2) {
              try {
                keys = this.keysInFile(await this.plugin.app.vault.cachedRead(file), file);
              } catch {
                return;
              }
            }
            if (!keys.has(key) && !session.isAttached()) {
              session.dispose();
              this.sessions.delete(key);
            }
          }, 5e3)
        );
      }
      keysInFile(content, file) {
        let texts = [content];
        if (file.extension === "canvas") {
          const data = JSON.parse(content);
          texts = (data.nodes || []).filter((n) => n.type === "text").map((n) => n.text || "");
        }
        const keys = /* @__PURE__ */ new Set();
        const fence = new RegExp("^(`{3,}|~{3,})[ \\t]*" + BLOCK_LANG2 + "[ \\t]*\\r?\\n([\\s\\S]*?)^\\1[ \\t]*$", "gm");
        for (const text of texts) {
          for (const m of text.matchAll(fence)) keys.add(blockKey(m[2], file.path));
        }
        return keys;
      }
      disposeAll() {
        for (const session of this.sessions.values()) session.dispose();
        this.sessions.clear();
        for (const timer of this.orphanTimers.values()) clearTimeout(timer);
        this.orphanTimers.clear();
      }
    };
    module2.exports = { BlockSessions: BlockSessions2, parseBlockOptions, blockKey, newBlockMarkdown: newBlockMarkdown2 };
  }
});

// src/canvas.js
var require_canvas = __commonJS({
  "src/canvas.js"(exports2, module2) {
    "use strict";
    var { ItemView, Notice: Notice2 } = require("obsidian");
    var { newBlockMarkdown: newBlockMarkdown2 } = require_block_sessions();
    function getActiveCanvas2(app) {
      const view = app.workspace.getActiveViewOfType(ItemView);
      return view && view.getViewType() === "canvas" && view.canvas ? view.canvas : null;
    }
    function addTerminalToCanvas2(canvas) {
      if (typeof canvas.createTextNode !== "function") {
        new Notice2("This Obsidian version doesn't allow plugins to create cards. Create a text card with a ```terminal block instead.");
        return;
      }
      const center = typeof canvas.posCenter === "function" ? canvas.posCenter() : { x: 0, y: 0 };
      canvas.createTextNode({
        pos: center,
        position: "center",
        size: { width: 640, height: 380 },
        text: newBlockMarkdown2(),
        focus: false,
        save: true
      });
      if (typeof canvas.requestSave === "function") canvas.requestSave();
    }
    module2.exports = { getActiveCanvas: getActiveCanvas2, addTerminalToCanvas: addTerminalToCanvas2 };
  }
});

// src/settings-tab.js
var require_settings_tab = __commonJS({
  "src/settings-tab.js"(exports2, module2) {
    "use strict";
    var { PluginSettingTab, Setting } = require("obsidian");
    var OpenTerminalSettingTab2 = class extends PluginSettingTab {
      constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
      }
      display() {
        const { containerEl } = this;
        containerEl.empty();
        const s = this.plugin.settings;
        const save = () => this.plugin.saveSettings();
        new Setting(containerEl).setName("Shell").setDesc("Shell launched inside the embedded terminal.").addDropdown((dd) => {
          dd.addOption("auto", "Automatic (recommended)");
          if (process.platform === "win32") {
            dd.addOption("powershell", "Windows PowerShell");
            dd.addOption("pwsh", "PowerShell 7 (pwsh)");
            dd.addOption("cmd", "Command Prompt (cmd)");
          } else {
            dd.addOption("zsh", "Zsh");
            dd.addOption("bash", "Bash");
          }
          dd.addOption("custom", "Custom");
          dd.setValue(s.shell).onChange(async (v) => {
            s.shell = v;
            await save();
            this.display();
          });
        });
        if (s.shell === "custom") {
          new Setting(containerEl).setName("Custom shell").setDesc('Executable and arguments. E.g.: "C:\\Program Files\\Git\\bin\\bash.exe" --login').addText(
            (t) => t.setValue(s.customShell).onChange(async (v) => {
              s.customShell = v;
              await save();
            })
          );
        }
        new Setting(containerEl).setName("Where to open").addDropdown(
          (dd) => dd.addOption("bottom", "Split panel below").addOption("tab", "New tab").addOption("right", "Right sidebar").setValue(s.location).onChange(async (v) => {
            s.location = v;
            await save();
          })
        );
        new Setting(containerEl).setName("Font size").setDesc("Applies to terminals opened after the change.").addSlider(
          (sl) => sl.setLimits(9, 24, 1).setValue(s.fontSize).setDynamicTooltip().onChange(async (v) => {
            s.fontSize = v;
            await save();
          })
        );
        new Setting(containerEl).setName("Node.js path").setDesc(`Leave empty to auto-detect. Detected: ${this.plugin.resolveNodePath() || "none"}`).addText(
          (t) => t.setPlaceholder("C:\\Program Files\\nodejs\\node.exe").setValue(s.nodePath).onChange(async (v) => {
            s.nodePath = v;
            await save();
          })
        );
      }
    };
    module2.exports = { OpenTerminalSettingTab: OpenTerminalSettingTab2 };
  }
});

// src/main.js
var { Plugin, Notice, FileSystemAdapter, TFile, TFolder } = require("obsidian");
var path = require("path");
var { VIEW_TYPE, BLOCK_LANG, DEFAULT_SETTINGS } = require_constants();
var shell = require_shell();
var { TerminalView } = require_terminal_view();
var { BlockSessions, newBlockMarkdown } = require_block_sessions();
var { getActiveCanvas, addTerminalToCanvas } = require_canvas();
var { OpenTerminalSettingTab } = require_settings_tab();
var OpenTerminalPlugin = class extends Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE, (leaf) => new TerminalView(leaf, this));
    this.addRibbonIcon("terminal-square", "Open terminal", () => {
      this.openTerminal(this.getVaultPath());
    });
    this.addCommand({
      id: "open-terminal-vault",
      name: "Open terminal at vault root",
      callback: () => this.openTerminal(this.getVaultPath())
    });
    this.addCommand({
      id: "open-terminal-current-folder",
      name: "Open terminal at current note's folder",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file) return false;
        if (!checking) this.openTerminal(this.getAbsolutePath(file.parent));
        return true;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        const folder = file instanceof TFolder ? file : file instanceof TFile ? file.parent : null;
        if (!folder) return;
        menu.addItem(
          (item) => item.setTitle("Open in terminal").setIcon("terminal-square").onClick(() => this.openTerminal(this.getAbsolutePath(folder)))
        );
      })
    );
    this.blocks = new BlockSessions(this);
    this.registerMarkdownCodeBlockProcessor(BLOCK_LANG, (source, el, ctx) => this.blocks.process(source, el, ctx));
    this.addCommand({
      id: "insert-terminal-block",
      name: "Insert terminal into note",
      editorCallback: (editor) => editor.replaceSelection(newBlockMarkdown() + "\n")
    });
    this.addCommand({
      id: "add-terminal-to-canvas",
      name: "Add terminal to canvas",
      checkCallback: (checking) => {
        const canvas = getActiveCanvas(this.app);
        if (!canvas) return false;
        if (!checking) addTerminalToCanvas(canvas);
        return true;
      }
    });
    this.addSettingTab(new OpenTerminalSettingTab(this.app, this));
  }
  onunload() {
    this.blocks.disposeAll();
  }
  /**
   * Public API for other plugins: opens a terminal and runs a command.
   * E.g.: app.plugins.plugins["open-terminal"].runInTerminal("claude", { cwd })
   */
  async runInTerminal(command, { cwd, reuse = false } = {}) {
    cwd = cwd || this.getVaultPath();
    if (reuse) {
      const view = this.getTerminals().find((v) => v.isAtPrompt());
      if (view) {
        view.reveal();
        view.sendText(`${this.cdCommand(cwd)} ${this.shellSeparator()} ${command}`);
        return view;
      }
    }
    return this.openTerminal(cwd, command);
  }
  /**
   * Open terminals: views (newest to oldest), then blocks visible in
   * notes/Canvas (most recently used first).
   */
  getTerminals() {
    const views = this.app.workspace.getLeavesOfType(VIEW_TYPE).map((l) => l.view).filter((v) => v instanceof TerminalView).reverse();
    return [...views, ...this.blocks.visible()];
  }
  async openTerminal(cwd, command) {
    if (!cwd) {
      new Notice("Could not determine the folder path.");
      return;
    }
    const { workspace } = this.app;
    let leaf;
    switch (this.settings.location) {
      case "tab":
        leaf = workspace.getLeaf("tab");
        break;
      case "right":
        leaf = workspace.getRightLeaf(false);
        break;
      default:
        leaf = workspace.getLeaf("split", "horizontal");
    }
    await leaf.setViewState({ type: VIEW_TYPE, active: true, state: { cwd, command } });
    workspace.revealLeaf(leaf);
    return leaf.view;
  }
  loadXterm() {
    if (!this.xterm) {
      const base = path.join(this.pluginDir(), "node_modules", "@xterm");
      const { Terminal } = window.require(path.join(base, "xterm", "lib", "xterm.js"));
      const { FitAddon } = window.require(path.join(base, "addon-fit", "lib", "addon-fit.js"));
      this.xterm = { Terminal, FitAddon };
    }
    return this.xterm;
  }
  getShell() {
    return shell.getShell(this.settings);
  }
  resolveNodePath() {
    return shell.resolveNodePath(this.settings);
  }
  cdCommand(dir) {
    return shell.cdCommand(this.getShell().cmd, dir);
  }
  shellSeparator() {
    return shell.shellSeparator(this.getShell().cmd);
  }
  quoteArg(arg) {
    return shell.quoteArg(this.getShell().cmd, arg);
  }
  pluginDir() {
    return path.join(this.getVaultPath(), this.manifest.dir);
  }
  hostPath() {
    return path.join(this.pluginDir(), "pty-host.js");
  }
  getVaultPath() {
    const adapter = this.app.vault.adapter;
    if (adapter instanceof FileSystemAdapter) return adapter.getBasePath();
    return null;
  }
  getAbsolutePath(folder) {
    const base = this.getVaultPath();
    if (!base) return null;
    if (!folder || folder.isRoot()) return base;
    return path.join(base, folder.path);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
module.exports = OpenTerminalPlugin;
